// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.example.tutorial.nano;

@SuppressWarnings("hiding")
public interface AddressBookProto {

  public static final class Address extends
      com.google.protobuf.nano.MessageNano {

    // enum PhoneType
    public static final int MOBILE = 0;
    public static final int HOME = 1;
    public static final int WORK = 2;

    public static final class PhoneNumber extends
        com.google.protobuf.nano.MessageNano {

      private static volatile PhoneNumber[] _emptyArray;
      public static PhoneNumber[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new PhoneNumber[0];
            }
          }
        }
        return _emptyArray;
      }

      // required string number = 1;
      public java.lang.String number;

      // optional .tutorial.Address.PhoneType type = 2 [default = HOME];
      public int type;

      public PhoneNumber() {
        clear();
      }

      public PhoneNumber clear() {
        number = "";
        type = com.example.tutorial.nano.AddressBookProto.Address.HOME;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        output.writeString(1, this.number);
        if (this.type != com.example.tutorial.nano.AddressBookProto.Address.HOME) {
          output.writeInt32(2, this.type);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.number);
        if (this.type != com.example.tutorial.nano.AddressBookProto.Address.HOME) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.type);
        }
        return size;
      }

      @Override
      public PhoneNumber mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.number = input.readString();
              break;
            }
            case 16: {
              int value = input.readInt32();
              switch (value) {
                case com.example.tutorial.nano.AddressBookProto.Address.MOBILE:
                case com.example.tutorial.nano.AddressBookProto.Address.HOME:
                case com.example.tutorial.nano.AddressBookProto.Address.WORK:
                  this.type = value;
                  break;
              }
              break;
            }
          }
        }
      }

      public static PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new PhoneNumber(), data);
      }

      public static PhoneNumber parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new PhoneNumber().mergeFrom(input);
      }
    }

    private static volatile Address[] _emptyArray;
    public static Address[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Address[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string name = 1;
    public java.lang.String name;

    // required int32 id = 2;
    public int id;

    // optional string email = 3;
    public java.lang.String email;

    // repeated .tutorial.Address.PhoneNumber phones = 4;
    public com.example.tutorial.nano.AddressBookProto.Address.PhoneNumber[] phones;

    public Address() {
      clear();
    }

    public Address clear() {
      name = "";
      id = 0;
      email = "";
      phones = com.example.tutorial.nano.AddressBookProto.Address.PhoneNumber.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.name);
      output.writeInt32(2, this.id);
      if (!this.email.equals("")) {
        output.writeString(3, this.email);
      }
      if (this.phones != null && this.phones.length > 0) {
        for (int i = 0; i < this.phones.length; i++) {
          com.example.tutorial.nano.AddressBookProto.Address.PhoneNumber element = this.phones[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.name);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(2, this.id);
      if (!this.email.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.email);
      }
      if (this.phones != null && this.phones.length > 0) {
        for (int i = 0; i < this.phones.length; i++) {
          com.example.tutorial.nano.AddressBookProto.Address.PhoneNumber element = this.phones[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      return size;
    }

    @Override
    public Address mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.name = input.readString();
            break;
          }
          case 16: {
            this.id = input.readInt32();
            break;
          }
          case 26: {
            this.email = input.readString();
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.phones == null ? 0 : this.phones.length;
            com.example.tutorial.nano.AddressBookProto.Address.PhoneNumber[] newArray =
                new com.example.tutorial.nano.AddressBookProto.Address.PhoneNumber[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.phones, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.example.tutorial.nano.AddressBookProto.Address.PhoneNumber();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.example.tutorial.nano.AddressBookProto.Address.PhoneNumber();
            input.readMessage(newArray[i]);
            this.phones = newArray;
            break;
          }
        }
      }
    }

    public static Address parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Address(), data);
    }

    public static Address parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Address().mergeFrom(input);
    }
  }

  public static final class AddressBook extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AddressBook[] _emptyArray;
    public static AddressBook[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AddressBook[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .tutorial.Address people = 1;
    public com.example.tutorial.nano.AddressBookProto.Address[] people;

    public AddressBook() {
      clear();
    }

    public AddressBook clear() {
      people = com.example.tutorial.nano.AddressBookProto.Address.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.people != null && this.people.length > 0) {
        for (int i = 0; i < this.people.length; i++) {
          com.example.tutorial.nano.AddressBookProto.Address element = this.people[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.people != null && this.people.length > 0) {
        for (int i = 0; i < this.people.length; i++) {
          com.example.tutorial.nano.AddressBookProto.Address element = this.people[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public AddressBook mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.people == null ? 0 : this.people.length;
            com.example.tutorial.nano.AddressBookProto.Address[] newArray =
                new com.example.tutorial.nano.AddressBookProto.Address[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.people, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.example.tutorial.nano.AddressBookProto.Address();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.example.tutorial.nano.AddressBookProto.Address();
            input.readMessage(newArray[i]);
            this.people = newArray;
            break;
          }
        }
      }
    }

    public static AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AddressBook(), data);
    }

    public static AddressBook parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AddressBook().mergeFrom(input);
    }
  }
}
