// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: array.proto

package cn.pojo;

public final class Array {
  private Array() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ArrayProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ArrayProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 ages = 1;</code>
     */
    java.util.List<java.lang.Integer> getAgesList();
    /**
     * <code>repeated int32 ages = 1;</code>
     */
    int getAgesCount();
    /**
     * <code>repeated int32 ages = 1;</code>
     */
    int getAges(int index);

    /**
     * <code>repeated string names = 2;</code>
     */
    java.util.List<java.lang.String>
        getNamesList();
    /**
     * <code>repeated string names = 2;</code>
     */
    int getNamesCount();
    /**
     * <code>repeated string names = 2;</code>
     */
    java.lang.String getNames(int index);
    /**
     * <code>repeated string names = 2;</code>
     */
    com.google.protobuf.ByteString
        getNamesBytes(int index);

    /**
     * <code>map&lt;int32, string&gt; student = 3;</code>
     */
    int getStudentCount();
    /**
     * <code>map&lt;int32, string&gt; student = 3;</code>
     */
    boolean containsStudent(
        int key);
    /**
     * Use {@link #getStudentMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.String>
    getStudent();
    /**
     * <code>map&lt;int32, string&gt; student = 3;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.String>
    getStudentMap();
    /**
     * <code>map&lt;int32, string&gt; student = 3;</code>
     */

    java.lang.String getStudentOrDefault(
        int key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;int32, string&gt; student = 3;</code>
     */

    java.lang.String getStudentOrThrow(
        int key);

    /**
     * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
     */
    int getBasicCount();
    /**
     * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
     */
    boolean containsBasic(
        java.lang.String key);
    /**
     * Use {@link #getBasicMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, cn.pojo.Basic.BasicProto>
    getBasic();
    /**
     * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
     */
    java.util.Map<java.lang.String, cn.pojo.Basic.BasicProto>
    getBasicMap();
    /**
     * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
     */

    cn.pojo.Basic.BasicProto getBasicOrDefault(
        java.lang.String key,
        cn.pojo.Basic.BasicProto defaultValue);
    /**
     * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
     */

    cn.pojo.Basic.BasicProto getBasicOrThrow(
        java.lang.String key);

    /**
     * <code>.ArrayProto.Lists list = 6;</code>
     */
    boolean hasList();
    /**
     * <code>.ArrayProto.Lists list = 6;</code>
     */
    cn.pojo.Array.ArrayProto.Lists getList();
    /**
     * <code>.ArrayProto.Lists list = 6;</code>
     */
    cn.pojo.Array.ArrayProto.ListsOrBuilder getListOrBuilder();
  }
  /**
   * Protobuf type {@code ArrayProto}
   */
  public  static final class ArrayProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ArrayProto)
      ArrayProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ArrayProto.newBuilder() to construct.
    private ArrayProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ArrayProto() {
      ages_ = java.util.Collections.emptyList();
      names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ArrayProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ages_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              ages_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                ages_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                ages_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                names_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              names_.add(s);
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                student_ = com.google.protobuf.MapField.newMapField(
                    StudentDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
              student__ = input.readMessage(
                  StudentDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              student_.getMutableMap().put(
                  student__.getKey(), student__.getValue());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                basic_ = com.google.protobuf.MapField.newMapField(
                    BasicDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, cn.pojo.Basic.BasicProto>
              basic__ = input.readMessage(
                  BasicDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              basic_.getMutableMap().put(
                  basic__.getKey(), basic__.getValue());
              break;
            }
            case 50: {
              cn.pojo.Array.ArrayProto.Lists.Builder subBuilder = null;
              if (list_ != null) {
                subBuilder = list_.toBuilder();
              }
              list_ = input.readMessage(cn.pojo.Array.ArrayProto.Lists.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(list_);
                list_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          ages_ = java.util.Collections.unmodifiableList(ages_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          names_ = names_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.pojo.Array.internal_static_ArrayProto_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetStudent();
        case 4:
          return internalGetBasic();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.pojo.Array.internal_static_ArrayProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.pojo.Array.ArrayProto.class, cn.pojo.Array.ArrayProto.Builder.class);
    }

    public interface ListsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ArrayProto.Lists)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
       */
      java.util.List<cn.pojo.Nest.NestProto.Dinosaur> 
          getDinosaurList();
      /**
       * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
       */
      cn.pojo.Nest.NestProto.Dinosaur getDinosaur(int index);
      /**
       * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
       */
      int getDinosaurCount();
      /**
       * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
       */
      java.util.List<? extends cn.pojo.Nest.NestProto.DinosaurOrBuilder> 
          getDinosaurOrBuilderList();
      /**
       * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
       */
      cn.pojo.Nest.NestProto.DinosaurOrBuilder getDinosaurOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code ArrayProto.Lists}
     */
    public  static final class Lists extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ArrayProto.Lists)
        ListsOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Lists.newBuilder() to construct.
      private Lists(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Lists() {
        dinosaur_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Lists(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 42: {
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  dinosaur_ = new java.util.ArrayList<cn.pojo.Nest.NestProto.Dinosaur>();
                  mutable_bitField0_ |= 0x00000001;
                }
                dinosaur_.add(
                    input.readMessage(cn.pojo.Nest.NestProto.Dinosaur.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            dinosaur_ = java.util.Collections.unmodifiableList(dinosaur_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.pojo.Array.internal_static_ArrayProto_Lists_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.pojo.Array.internal_static_ArrayProto_Lists_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.pojo.Array.ArrayProto.Lists.class, cn.pojo.Array.ArrayProto.Lists.Builder.class);
      }

      public static final int DINOSAUR_FIELD_NUMBER = 5;
      private java.util.List<cn.pojo.Nest.NestProto.Dinosaur> dinosaur_;
      /**
       * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
       */
      public java.util.List<cn.pojo.Nest.NestProto.Dinosaur> getDinosaurList() {
        return dinosaur_;
      }
      /**
       * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
       */
      public java.util.List<? extends cn.pojo.Nest.NestProto.DinosaurOrBuilder> 
          getDinosaurOrBuilderList() {
        return dinosaur_;
      }
      /**
       * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
       */
      public int getDinosaurCount() {
        return dinosaur_.size();
      }
      /**
       * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
       */
      public cn.pojo.Nest.NestProto.Dinosaur getDinosaur(int index) {
        return dinosaur_.get(index);
      }
      /**
       * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
       */
      public cn.pojo.Nest.NestProto.DinosaurOrBuilder getDinosaurOrBuilder(
          int index) {
        return dinosaur_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < dinosaur_.size(); i++) {
          output.writeMessage(5, dinosaur_.get(i));
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < dinosaur_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, dinosaur_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof cn.pojo.Array.ArrayProto.Lists)) {
          return super.equals(obj);
        }
        cn.pojo.Array.ArrayProto.Lists other = (cn.pojo.Array.ArrayProto.Lists) obj;

        boolean result = true;
        result = result && getDinosaurList()
            .equals(other.getDinosaurList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getDinosaurCount() > 0) {
          hash = (37 * hash) + DINOSAUR_FIELD_NUMBER;
          hash = (53 * hash) + getDinosaurList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static cn.pojo.Array.ArrayProto.Lists parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.pojo.Array.ArrayProto.Lists parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.pojo.Array.ArrayProto.Lists parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.pojo.Array.ArrayProto.Lists parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.pojo.Array.ArrayProto.Lists parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.pojo.Array.ArrayProto.Lists parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.pojo.Array.ArrayProto.Lists parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cn.pojo.Array.ArrayProto.Lists parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.pojo.Array.ArrayProto.Lists parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static cn.pojo.Array.ArrayProto.Lists parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.pojo.Array.ArrayProto.Lists parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cn.pojo.Array.ArrayProto.Lists parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(cn.pojo.Array.ArrayProto.Lists prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ArrayProto.Lists}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ArrayProto.Lists)
          cn.pojo.Array.ArrayProto.ListsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return cn.pojo.Array.internal_static_ArrayProto_Lists_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return cn.pojo.Array.internal_static_ArrayProto_Lists_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  cn.pojo.Array.ArrayProto.Lists.class, cn.pojo.Array.ArrayProto.Lists.Builder.class);
        }

        // Construct using cn.pojo.Array.ArrayProto.Lists.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getDinosaurFieldBuilder();
          }
        }
        public Builder clear() {
          super.clear();
          if (dinosaurBuilder_ == null) {
            dinosaur_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            dinosaurBuilder_.clear();
          }
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return cn.pojo.Array.internal_static_ArrayProto_Lists_descriptor;
        }

        public cn.pojo.Array.ArrayProto.Lists getDefaultInstanceForType() {
          return cn.pojo.Array.ArrayProto.Lists.getDefaultInstance();
        }

        public cn.pojo.Array.ArrayProto.Lists build() {
          cn.pojo.Array.ArrayProto.Lists result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public cn.pojo.Array.ArrayProto.Lists buildPartial() {
          cn.pojo.Array.ArrayProto.Lists result = new cn.pojo.Array.ArrayProto.Lists(this);
          int from_bitField0_ = bitField0_;
          if (dinosaurBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              dinosaur_ = java.util.Collections.unmodifiableList(dinosaur_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.dinosaur_ = dinosaur_;
          } else {
            result.dinosaur_ = dinosaurBuilder_.build();
          }
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof cn.pojo.Array.ArrayProto.Lists) {
            return mergeFrom((cn.pojo.Array.ArrayProto.Lists)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(cn.pojo.Array.ArrayProto.Lists other) {
          if (other == cn.pojo.Array.ArrayProto.Lists.getDefaultInstance()) return this;
          if (dinosaurBuilder_ == null) {
            if (!other.dinosaur_.isEmpty()) {
              if (dinosaur_.isEmpty()) {
                dinosaur_ = other.dinosaur_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureDinosaurIsMutable();
                dinosaur_.addAll(other.dinosaur_);
              }
              onChanged();
            }
          } else {
            if (!other.dinosaur_.isEmpty()) {
              if (dinosaurBuilder_.isEmpty()) {
                dinosaurBuilder_.dispose();
                dinosaurBuilder_ = null;
                dinosaur_ = other.dinosaur_;
                bitField0_ = (bitField0_ & ~0x00000001);
                dinosaurBuilder_ = 
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                     getDinosaurFieldBuilder() : null;
              } else {
                dinosaurBuilder_.addAllMessages(other.dinosaur_);
              }
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          cn.pojo.Array.ArrayProto.Lists parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (cn.pojo.Array.ArrayProto.Lists) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.util.List<cn.pojo.Nest.NestProto.Dinosaur> dinosaur_ =
          java.util.Collections.emptyList();
        private void ensureDinosaurIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            dinosaur_ = new java.util.ArrayList<cn.pojo.Nest.NestProto.Dinosaur>(dinosaur_);
            bitField0_ |= 0x00000001;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            cn.pojo.Nest.NestProto.Dinosaur, cn.pojo.Nest.NestProto.Dinosaur.Builder, cn.pojo.Nest.NestProto.DinosaurOrBuilder> dinosaurBuilder_;

        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public java.util.List<cn.pojo.Nest.NestProto.Dinosaur> getDinosaurList() {
          if (dinosaurBuilder_ == null) {
            return java.util.Collections.unmodifiableList(dinosaur_);
          } else {
            return dinosaurBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public int getDinosaurCount() {
          if (dinosaurBuilder_ == null) {
            return dinosaur_.size();
          } else {
            return dinosaurBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public cn.pojo.Nest.NestProto.Dinosaur getDinosaur(int index) {
          if (dinosaurBuilder_ == null) {
            return dinosaur_.get(index);
          } else {
            return dinosaurBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public Builder setDinosaur(
            int index, cn.pojo.Nest.NestProto.Dinosaur value) {
          if (dinosaurBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureDinosaurIsMutable();
            dinosaur_.set(index, value);
            onChanged();
          } else {
            dinosaurBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public Builder setDinosaur(
            int index, cn.pojo.Nest.NestProto.Dinosaur.Builder builderForValue) {
          if (dinosaurBuilder_ == null) {
            ensureDinosaurIsMutable();
            dinosaur_.set(index, builderForValue.build());
            onChanged();
          } else {
            dinosaurBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public Builder addDinosaur(cn.pojo.Nest.NestProto.Dinosaur value) {
          if (dinosaurBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureDinosaurIsMutable();
            dinosaur_.add(value);
            onChanged();
          } else {
            dinosaurBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public Builder addDinosaur(
            int index, cn.pojo.Nest.NestProto.Dinosaur value) {
          if (dinosaurBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureDinosaurIsMutable();
            dinosaur_.add(index, value);
            onChanged();
          } else {
            dinosaurBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public Builder addDinosaur(
            cn.pojo.Nest.NestProto.Dinosaur.Builder builderForValue) {
          if (dinosaurBuilder_ == null) {
            ensureDinosaurIsMutable();
            dinosaur_.add(builderForValue.build());
            onChanged();
          } else {
            dinosaurBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public Builder addDinosaur(
            int index, cn.pojo.Nest.NestProto.Dinosaur.Builder builderForValue) {
          if (dinosaurBuilder_ == null) {
            ensureDinosaurIsMutable();
            dinosaur_.add(index, builderForValue.build());
            onChanged();
          } else {
            dinosaurBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public Builder addAllDinosaur(
            java.lang.Iterable<? extends cn.pojo.Nest.NestProto.Dinosaur> values) {
          if (dinosaurBuilder_ == null) {
            ensureDinosaurIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, dinosaur_);
            onChanged();
          } else {
            dinosaurBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public Builder clearDinosaur() {
          if (dinosaurBuilder_ == null) {
            dinosaur_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            dinosaurBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public Builder removeDinosaur(int index) {
          if (dinosaurBuilder_ == null) {
            ensureDinosaurIsMutable();
            dinosaur_.remove(index);
            onChanged();
          } else {
            dinosaurBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public cn.pojo.Nest.NestProto.Dinosaur.Builder getDinosaurBuilder(
            int index) {
          return getDinosaurFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public cn.pojo.Nest.NestProto.DinosaurOrBuilder getDinosaurOrBuilder(
            int index) {
          if (dinosaurBuilder_ == null) {
            return dinosaur_.get(index);  } else {
            return dinosaurBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public java.util.List<? extends cn.pojo.Nest.NestProto.DinosaurOrBuilder> 
             getDinosaurOrBuilderList() {
          if (dinosaurBuilder_ != null) {
            return dinosaurBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(dinosaur_);
          }
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public cn.pojo.Nest.NestProto.Dinosaur.Builder addDinosaurBuilder() {
          return getDinosaurFieldBuilder().addBuilder(
              cn.pojo.Nest.NestProto.Dinosaur.getDefaultInstance());
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public cn.pojo.Nest.NestProto.Dinosaur.Builder addDinosaurBuilder(
            int index) {
          return getDinosaurFieldBuilder().addBuilder(
              index, cn.pojo.Nest.NestProto.Dinosaur.getDefaultInstance());
        }
        /**
         * <code>repeated .NestProto.Dinosaur dinosaur = 5;</code>
         */
        public java.util.List<cn.pojo.Nest.NestProto.Dinosaur.Builder> 
             getDinosaurBuilderList() {
          return getDinosaurFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
            cn.pojo.Nest.NestProto.Dinosaur, cn.pojo.Nest.NestProto.Dinosaur.Builder, cn.pojo.Nest.NestProto.DinosaurOrBuilder> 
            getDinosaurFieldBuilder() {
          if (dinosaurBuilder_ == null) {
            dinosaurBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                cn.pojo.Nest.NestProto.Dinosaur, cn.pojo.Nest.NestProto.Dinosaur.Builder, cn.pojo.Nest.NestProto.DinosaurOrBuilder>(
                    dinosaur_,
                    ((bitField0_ & 0x00000001) == 0x00000001),
                    getParentForChildren(),
                    isClean());
            dinosaur_ = null;
          }
          return dinosaurBuilder_;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:ArrayProto.Lists)
      }

      // @@protoc_insertion_point(class_scope:ArrayProto.Lists)
      private static final cn.pojo.Array.ArrayProto.Lists DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new cn.pojo.Array.ArrayProto.Lists();
      }

      public static cn.pojo.Array.ArrayProto.Lists getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Lists>
          PARSER = new com.google.protobuf.AbstractParser<Lists>() {
        public Lists parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Lists(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Lists> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Lists> getParserForType() {
        return PARSER;
      }

      public cn.pojo.Array.ArrayProto.Lists getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int AGES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> ages_;
    /**
     * <code>repeated int32 ages = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getAgesList() {
      return ages_;
    }
    /**
     * <code>repeated int32 ages = 1;</code>
     */
    public int getAgesCount() {
      return ages_.size();
    }
    /**
     * <code>repeated int32 ages = 1;</code>
     */
    public int getAges(int index) {
      return ages_.get(index);
    }
    private int agesMemoizedSerializedSize = -1;

    public static final int NAMES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList names_;
    /**
     * <code>repeated string names = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNamesList() {
      return names_;
    }
    /**
     * <code>repeated string names = 2;</code>
     */
    public int getNamesCount() {
      return names_.size();
    }
    /**
     * <code>repeated string names = 2;</code>
     */
    public java.lang.String getNames(int index) {
      return names_.get(index);
    }
    /**
     * <code>repeated string names = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNamesBytes(int index) {
      return names_.getByteString(index);
    }

    public static final int STUDENT_FIELD_NUMBER = 3;
    private static final class StudentDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.String>newDefaultInstance(
                  cn.pojo.Array.internal_static_ArrayProto_StudentEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> student_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
    internalGetStudent() {
      if (student_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StudentDefaultEntryHolder.defaultEntry);
      }
      return student_;
    }

    public int getStudentCount() {
      return internalGetStudent().getMap().size();
    }
    /**
     * <code>map&lt;int32, string&gt; student = 3;</code>
     */

    public boolean containsStudent(
        int key) {
      
      return internalGetStudent().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStudentMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String> getStudent() {
      return getStudentMap();
    }
    /**
     * <code>map&lt;int32, string&gt; student = 3;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.String> getStudentMap() {
      return internalGetStudent().getMap();
    }
    /**
     * <code>map&lt;int32, string&gt; student = 3;</code>
     */

    public java.lang.String getStudentOrDefault(
        int key,
        java.lang.String defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetStudent().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, string&gt; student = 3;</code>
     */

    public java.lang.String getStudentOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetStudent().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int BASIC_FIELD_NUMBER = 4;
    private static final class BasicDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, cn.pojo.Basic.BasicProto> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, cn.pojo.Basic.BasicProto>newDefaultInstance(
                  cn.pojo.Array.internal_static_ArrayProto_BasicEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  cn.pojo.Basic.BasicProto.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, cn.pojo.Basic.BasicProto> basic_;
    private com.google.protobuf.MapField<java.lang.String, cn.pojo.Basic.BasicProto>
    internalGetBasic() {
      if (basic_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            BasicDefaultEntryHolder.defaultEntry);
      }
      return basic_;
    }

    public int getBasicCount() {
      return internalGetBasic().getMap().size();
    }
    /**
     * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
     */

    public boolean containsBasic(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetBasic().getMap().containsKey(key);
    }
    /**
     * Use {@link #getBasicMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, cn.pojo.Basic.BasicProto> getBasic() {
      return getBasicMap();
    }
    /**
     * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
     */

    public java.util.Map<java.lang.String, cn.pojo.Basic.BasicProto> getBasicMap() {
      return internalGetBasic().getMap();
    }
    /**
     * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
     */

    public cn.pojo.Basic.BasicProto getBasicOrDefault(
        java.lang.String key,
        cn.pojo.Basic.BasicProto defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, cn.pojo.Basic.BasicProto> map =
          internalGetBasic().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
     */

    public cn.pojo.Basic.BasicProto getBasicOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, cn.pojo.Basic.BasicProto> map =
          internalGetBasic().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int LIST_FIELD_NUMBER = 6;
    private cn.pojo.Array.ArrayProto.Lists list_;
    /**
     * <code>.ArrayProto.Lists list = 6;</code>
     */
    public boolean hasList() {
      return list_ != null;
    }
    /**
     * <code>.ArrayProto.Lists list = 6;</code>
     */
    public cn.pojo.Array.ArrayProto.Lists getList() {
      return list_ == null ? cn.pojo.Array.ArrayProto.Lists.getDefaultInstance() : list_;
    }
    /**
     * <code>.ArrayProto.Lists list = 6;</code>
     */
    public cn.pojo.Array.ArrayProto.ListsOrBuilder getListOrBuilder() {
      return getList();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getAgesList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(agesMemoizedSerializedSize);
      }
      for (int i = 0; i < ages_.size(); i++) {
        output.writeInt32NoTag(ages_.get(i));
      }
      for (int i = 0; i < names_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, names_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetStudent(),
          StudentDefaultEntryHolder.defaultEntry,
          3);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetBasic(),
          BasicDefaultEntryHolder.defaultEntry,
          4);
      if (list_ != null) {
        output.writeMessage(6, getList());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < ages_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(ages_.get(i));
        }
        size += dataSize;
        if (!getAgesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        agesMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < names_.size(); i++) {
          dataSize += computeStringSizeNoTag(names_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getNamesList().size();
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
           : internalGetStudent().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
        student__ = StudentDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, student__);
      }
      for (java.util.Map.Entry<java.lang.String, cn.pojo.Basic.BasicProto> entry
           : internalGetBasic().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, cn.pojo.Basic.BasicProto>
        basic__ = BasicDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, basic__);
      }
      if (list_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getList());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.pojo.Array.ArrayProto)) {
        return super.equals(obj);
      }
      cn.pojo.Array.ArrayProto other = (cn.pojo.Array.ArrayProto) obj;

      boolean result = true;
      result = result && getAgesList()
          .equals(other.getAgesList());
      result = result && getNamesList()
          .equals(other.getNamesList());
      result = result && internalGetStudent().equals(
          other.internalGetStudent());
      result = result && internalGetBasic().equals(
          other.internalGetBasic());
      result = result && (hasList() == other.hasList());
      if (hasList()) {
        result = result && getList()
            .equals(other.getList());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAgesCount() > 0) {
        hash = (37 * hash) + AGES_FIELD_NUMBER;
        hash = (53 * hash) + getAgesList().hashCode();
      }
      if (getNamesCount() > 0) {
        hash = (37 * hash) + NAMES_FIELD_NUMBER;
        hash = (53 * hash) + getNamesList().hashCode();
      }
      if (!internalGetStudent().getMap().isEmpty()) {
        hash = (37 * hash) + STUDENT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetStudent().hashCode();
      }
      if (!internalGetBasic().getMap().isEmpty()) {
        hash = (37 * hash) + BASIC_FIELD_NUMBER;
        hash = (53 * hash) + internalGetBasic().hashCode();
      }
      if (hasList()) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.pojo.Array.ArrayProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Array.ArrayProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Array.ArrayProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Array.ArrayProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Array.ArrayProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Array.ArrayProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Array.ArrayProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.pojo.Array.ArrayProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.pojo.Array.ArrayProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.pojo.Array.ArrayProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.pojo.Array.ArrayProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.pojo.Array.ArrayProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.pojo.Array.ArrayProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ArrayProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ArrayProto)
        cn.pojo.Array.ArrayProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.pojo.Array.internal_static_ArrayProto_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetStudent();
          case 4:
            return internalGetBasic();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableStudent();
          case 4:
            return internalGetMutableBasic();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.pojo.Array.internal_static_ArrayProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.pojo.Array.ArrayProto.class, cn.pojo.Array.ArrayProto.Builder.class);
      }

      // Construct using cn.pojo.Array.ArrayProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableStudent().clear();
        internalGetMutableBasic().clear();
        if (listBuilder_ == null) {
          list_ = null;
        } else {
          list_ = null;
          listBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.pojo.Array.internal_static_ArrayProto_descriptor;
      }

      public cn.pojo.Array.ArrayProto getDefaultInstanceForType() {
        return cn.pojo.Array.ArrayProto.getDefaultInstance();
      }

      public cn.pojo.Array.ArrayProto build() {
        cn.pojo.Array.ArrayProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.pojo.Array.ArrayProto buildPartial() {
        cn.pojo.Array.ArrayProto result = new cn.pojo.Array.ArrayProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          ages_ = java.util.Collections.unmodifiableList(ages_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ages_ = ages_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          names_ = names_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.names_ = names_;
        result.student_ = internalGetStudent();
        result.student_.makeImmutable();
        result.basic_ = internalGetBasic();
        result.basic_.makeImmutable();
        if (listBuilder_ == null) {
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.pojo.Array.ArrayProto) {
          return mergeFrom((cn.pojo.Array.ArrayProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.pojo.Array.ArrayProto other) {
        if (other == cn.pojo.Array.ArrayProto.getDefaultInstance()) return this;
        if (!other.ages_.isEmpty()) {
          if (ages_.isEmpty()) {
            ages_ = other.ages_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAgesIsMutable();
            ages_.addAll(other.ages_);
          }
          onChanged();
        }
        if (!other.names_.isEmpty()) {
          if (names_.isEmpty()) {
            names_ = other.names_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureNamesIsMutable();
            names_.addAll(other.names_);
          }
          onChanged();
        }
        internalGetMutableStudent().mergeFrom(
            other.internalGetStudent());
        internalGetMutableBasic().mergeFrom(
            other.internalGetBasic());
        if (other.hasList()) {
          mergeList(other.getList());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.pojo.Array.ArrayProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.pojo.Array.ArrayProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> ages_ = java.util.Collections.emptyList();
      private void ensureAgesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ages_ = new java.util.ArrayList<java.lang.Integer>(ages_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 ages = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getAgesList() {
        return java.util.Collections.unmodifiableList(ages_);
      }
      /**
       * <code>repeated int32 ages = 1;</code>
       */
      public int getAgesCount() {
        return ages_.size();
      }
      /**
       * <code>repeated int32 ages = 1;</code>
       */
      public int getAges(int index) {
        return ages_.get(index);
      }
      /**
       * <code>repeated int32 ages = 1;</code>
       */
      public Builder setAges(
          int index, int value) {
        ensureAgesIsMutable();
        ages_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ages = 1;</code>
       */
      public Builder addAges(int value) {
        ensureAgesIsMutable();
        ages_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ages = 1;</code>
       */
      public Builder addAllAges(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAgesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ages_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ages = 1;</code>
       */
      public Builder clearAges() {
        ages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNamesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          names_ = new com.google.protobuf.LazyStringArrayList(names_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string names = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getNamesList() {
        return names_.getUnmodifiableView();
      }
      /**
       * <code>repeated string names = 2;</code>
       */
      public int getNamesCount() {
        return names_.size();
      }
      /**
       * <code>repeated string names = 2;</code>
       */
      public java.lang.String getNames(int index) {
        return names_.get(index);
      }
      /**
       * <code>repeated string names = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNamesBytes(int index) {
        return names_.getByteString(index);
      }
      /**
       * <code>repeated string names = 2;</code>
       */
      public Builder setNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
        names_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 2;</code>
       */
      public Builder addNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
        names_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 2;</code>
       */
      public Builder addAllNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, names_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 2;</code>
       */
      public Builder clearNames() {
        names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string names = 2;</code>
       */
      public Builder addNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureNamesIsMutable();
        names_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.String> student_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetStudent() {
        if (student_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              StudentDefaultEntryHolder.defaultEntry);
        }
        return student_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetMutableStudent() {
        onChanged();;
        if (student_ == null) {
          student_ = com.google.protobuf.MapField.newMapField(
              StudentDefaultEntryHolder.defaultEntry);
        }
        if (!student_.isMutable()) {
          student_ = student_.copy();
        }
        return student_;
      }

      public int getStudentCount() {
        return internalGetStudent().getMap().size();
      }
      /**
       * <code>map&lt;int32, string&gt; student = 3;</code>
       */

      public boolean containsStudent(
          int key) {
        
        return internalGetStudent().getMap().containsKey(key);
      }
      /**
       * Use {@link #getStudentMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String> getStudent() {
        return getStudentMap();
      }
      /**
       * <code>map&lt;int32, string&gt; student = 3;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.String> getStudentMap() {
        return internalGetStudent().getMap();
      }
      /**
       * <code>map&lt;int32, string&gt; student = 3;</code>
       */

      public java.lang.String getStudentOrDefault(
          int key,
          java.lang.String defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetStudent().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, string&gt; student = 3;</code>
       */

      public java.lang.String getStudentOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetStudent().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearStudent() {
        internalGetMutableStudent().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, string&gt; student = 3;</code>
       */

      public Builder removeStudent(
          int key) {
        
        internalGetMutableStudent().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String>
      getMutableStudent() {
        return internalGetMutableStudent().getMutableMap();
      }
      /**
       * <code>map&lt;int32, string&gt; student = 3;</code>
       */
      public Builder putStudent(
          int key,
          java.lang.String value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableStudent().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, string&gt; student = 3;</code>
       */

      public Builder putAllStudent(
          java.util.Map<java.lang.Integer, java.lang.String> values) {
        internalGetMutableStudent().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, cn.pojo.Basic.BasicProto> basic_;
      private com.google.protobuf.MapField<java.lang.String, cn.pojo.Basic.BasicProto>
      internalGetBasic() {
        if (basic_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              BasicDefaultEntryHolder.defaultEntry);
        }
        return basic_;
      }
      private com.google.protobuf.MapField<java.lang.String, cn.pojo.Basic.BasicProto>
      internalGetMutableBasic() {
        onChanged();;
        if (basic_ == null) {
          basic_ = com.google.protobuf.MapField.newMapField(
              BasicDefaultEntryHolder.defaultEntry);
        }
        if (!basic_.isMutable()) {
          basic_ = basic_.copy();
        }
        return basic_;
      }

      public int getBasicCount() {
        return internalGetBasic().getMap().size();
      }
      /**
       * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
       */

      public boolean containsBasic(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetBasic().getMap().containsKey(key);
      }
      /**
       * Use {@link #getBasicMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, cn.pojo.Basic.BasicProto> getBasic() {
        return getBasicMap();
      }
      /**
       * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
       */

      public java.util.Map<java.lang.String, cn.pojo.Basic.BasicProto> getBasicMap() {
        return internalGetBasic().getMap();
      }
      /**
       * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
       */

      public cn.pojo.Basic.BasicProto getBasicOrDefault(
          java.lang.String key,
          cn.pojo.Basic.BasicProto defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, cn.pojo.Basic.BasicProto> map =
            internalGetBasic().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
       */

      public cn.pojo.Basic.BasicProto getBasicOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, cn.pojo.Basic.BasicProto> map =
            internalGetBasic().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearBasic() {
        internalGetMutableBasic().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
       */

      public Builder removeBasic(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableBasic().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, cn.pojo.Basic.BasicProto>
      getMutableBasic() {
        return internalGetMutableBasic().getMutableMap();
      }
      /**
       * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
       */
      public Builder putBasic(
          java.lang.String key,
          cn.pojo.Basic.BasicProto value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableBasic().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .BasicProto&gt; basic = 4;</code>
       */

      public Builder putAllBasic(
          java.util.Map<java.lang.String, cn.pojo.Basic.BasicProto> values) {
        internalGetMutableBasic().getMutableMap()
            .putAll(values);
        return this;
      }

      private cn.pojo.Array.ArrayProto.Lists list_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.pojo.Array.ArrayProto.Lists, cn.pojo.Array.ArrayProto.Lists.Builder, cn.pojo.Array.ArrayProto.ListsOrBuilder> listBuilder_;
      /**
       * <code>.ArrayProto.Lists list = 6;</code>
       */
      public boolean hasList() {
        return listBuilder_ != null || list_ != null;
      }
      /**
       * <code>.ArrayProto.Lists list = 6;</code>
       */
      public cn.pojo.Array.ArrayProto.Lists getList() {
        if (listBuilder_ == null) {
          return list_ == null ? cn.pojo.Array.ArrayProto.Lists.getDefaultInstance() : list_;
        } else {
          return listBuilder_.getMessage();
        }
      }
      /**
       * <code>.ArrayProto.Lists list = 6;</code>
       */
      public Builder setList(cn.pojo.Array.ArrayProto.Lists value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          list_ = value;
          onChanged();
        } else {
          listBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ArrayProto.Lists list = 6;</code>
       */
      public Builder setList(
          cn.pojo.Array.ArrayProto.Lists.Builder builderForValue) {
        if (listBuilder_ == null) {
          list_ = builderForValue.build();
          onChanged();
        } else {
          listBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ArrayProto.Lists list = 6;</code>
       */
      public Builder mergeList(cn.pojo.Array.ArrayProto.Lists value) {
        if (listBuilder_ == null) {
          if (list_ != null) {
            list_ =
              cn.pojo.Array.ArrayProto.Lists.newBuilder(list_).mergeFrom(value).buildPartial();
          } else {
            list_ = value;
          }
          onChanged();
        } else {
          listBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ArrayProto.Lists list = 6;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = null;
          onChanged();
        } else {
          list_ = null;
          listBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ArrayProto.Lists list = 6;</code>
       */
      public cn.pojo.Array.ArrayProto.Lists.Builder getListBuilder() {
        
        onChanged();
        return getListFieldBuilder().getBuilder();
      }
      /**
       * <code>.ArrayProto.Lists list = 6;</code>
       */
      public cn.pojo.Array.ArrayProto.ListsOrBuilder getListOrBuilder() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilder();
        } else {
          return list_ == null ?
              cn.pojo.Array.ArrayProto.Lists.getDefaultInstance() : list_;
        }
      }
      /**
       * <code>.ArrayProto.Lists list = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.pojo.Array.ArrayProto.Lists, cn.pojo.Array.ArrayProto.Lists.Builder, cn.pojo.Array.ArrayProto.ListsOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.pojo.Array.ArrayProto.Lists, cn.pojo.Array.ArrayProto.Lists.Builder, cn.pojo.Array.ArrayProto.ListsOrBuilder>(
                  getList(),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ArrayProto)
    }

    // @@protoc_insertion_point(class_scope:ArrayProto)
    private static final cn.pojo.Array.ArrayProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.pojo.Array.ArrayProto();
    }

    public static cn.pojo.Array.ArrayProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ArrayProto>
        PARSER = new com.google.protobuf.AbstractParser<ArrayProto>() {
      public ArrayProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ArrayProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ArrayProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ArrayProto> getParserForType() {
      return PARSER;
    }

    public cn.pojo.Array.ArrayProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ArrayProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ArrayProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ArrayProto_StudentEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ArrayProto_StudentEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ArrayProto_BasicEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ArrayProto_BasicEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ArrayProto_Lists_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ArrayProto_Lists_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013array.proto\032\013basic.proto\032\nnest.proto\"\267" +
      "\002\n\nArrayProto\022\014\n\004ages\030\001 \003(\005\022\r\n\005names\030\002 \003" +
      "(\t\022)\n\007student\030\003 \003(\0132\030.ArrayProto.Student" +
      "Entry\022%\n\005basic\030\004 \003(\0132\026.ArrayProto.BasicE" +
      "ntry\022\037\n\004list\030\006 \001(\0132\021.ArrayProto.Lists\032.\n" +
      "\014StudentEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(" +
      "\t:\0028\001\0329\n\nBasicEntry\022\013\n\003key\030\001 \001(\t\022\032\n\005valu" +
      "e\030\002 \001(\0132\013.BasicProto:\0028\001\032.\n\005Lists\022%\n\010din" +
      "osaur\030\005 \003(\0132\023.NestProto.DinosaurB\020\n\007cn.p" +
      "ojoB\005Arrayb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.pojo.Basic.getDescriptor(),
          cn.pojo.Nest.getDescriptor(),
        }, assigner);
    internal_static_ArrayProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ArrayProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ArrayProto_descriptor,
        new java.lang.String[] { "Ages", "Names", "Student", "Basic", "List", });
    internal_static_ArrayProto_StudentEntry_descriptor =
      internal_static_ArrayProto_descriptor.getNestedTypes().get(0);
    internal_static_ArrayProto_StudentEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ArrayProto_StudentEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ArrayProto_BasicEntry_descriptor =
      internal_static_ArrayProto_descriptor.getNestedTypes().get(1);
    internal_static_ArrayProto_BasicEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ArrayProto_BasicEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ArrayProto_Lists_descriptor =
      internal_static_ArrayProto_descriptor.getNestedTypes().get(2);
    internal_static_ArrayProto_Lists_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ArrayProto_Lists_descriptor,
        new java.lang.String[] { "Dinosaur", });
    cn.pojo.Basic.getDescriptor();
    cn.pojo.Nest.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
