// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basic.proto

package cn.pojo;

public final class Basic {
  private Basic() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BasicProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BasicProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double money = 1;</code>
     */
    double getMoney();

    /**
     * <code>float height = 2;</code>
     */
    float getHeight();

    /**
     * <code>int32 age = 3;</code>
     */
    int getAge();

    /**
     * <pre>
     * long
     * </pre>
     *
     * <code>int64 distance = 4;</code>
     */
    long getDistance();

    /**
     * <pre>
     * boolean
     * </pre>
     *
     * <code>bool sex = 5;</code>
     */
    boolean getSex();

    /**
     * <code>string name = 6;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 6;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code BasicProto}
   */
  public  static final class BasicProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BasicProto)
      BasicProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BasicProto.newBuilder() to construct.
    private BasicProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BasicProto() {
      money_ = 0D;
      height_ = 0F;
      age_ = 0;
      distance_ = 0L;
      sex_ = false;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BasicProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              money_ = input.readDouble();
              break;
            }
            case 21: {

              height_ = input.readFloat();
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 32: {

              distance_ = input.readInt64();
              break;
            }
            case 40: {

              sex_ = input.readBool();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.pojo.Basic.internal_static_BasicProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.pojo.Basic.internal_static_BasicProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.pojo.Basic.BasicProto.class, cn.pojo.Basic.BasicProto.Builder.class);
    }

    public static final int MONEY_FIELD_NUMBER = 1;
    private double money_;
    /**
     * <code>double money = 1;</code>
     */
    public double getMoney() {
      return money_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 2;
    private float height_;
    /**
     * <code>float height = 2;</code>
     */
    public float getHeight() {
      return height_;
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int DISTANCE_FIELD_NUMBER = 4;
    private long distance_;
    /**
     * <pre>
     * long
     * </pre>
     *
     * <code>int64 distance = 4;</code>
     */
    public long getDistance() {
      return distance_;
    }

    public static final int SEX_FIELD_NUMBER = 5;
    private boolean sex_;
    /**
     * <pre>
     * boolean
     * </pre>
     *
     * <code>bool sex = 5;</code>
     */
    public boolean getSex() {
      return sex_;
    }

    public static final int NAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 6;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (money_ != 0D) {
        output.writeDouble(1, money_);
      }
      if (height_ != 0F) {
        output.writeFloat(2, height_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      if (distance_ != 0L) {
        output.writeInt64(4, distance_);
      }
      if (sex_ != false) {
        output.writeBool(5, sex_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (money_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, money_);
      }
      if (height_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, height_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      if (distance_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, distance_);
      }
      if (sex_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, sex_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.pojo.Basic.BasicProto)) {
        return super.equals(obj);
      }
      cn.pojo.Basic.BasicProto other = (cn.pojo.Basic.BasicProto) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getMoney())
          == java.lang.Double.doubleToLongBits(
              other.getMoney()));
      result = result && (
          java.lang.Float.floatToIntBits(getHeight())
          == java.lang.Float.floatToIntBits(
              other.getHeight()));
      result = result && (getAge()
          == other.getAge());
      result = result && (getDistance()
          == other.getDistance());
      result = result && (getSex()
          == other.getSex());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MONEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMoney()));
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHeight());
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDistance());
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSex());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.pojo.Basic.BasicProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Basic.BasicProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Basic.BasicProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Basic.BasicProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Basic.BasicProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Basic.BasicProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Basic.BasicProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.pojo.Basic.BasicProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.pojo.Basic.BasicProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.pojo.Basic.BasicProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.pojo.Basic.BasicProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.pojo.Basic.BasicProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.pojo.Basic.BasicProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BasicProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BasicProto)
        cn.pojo.Basic.BasicProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.pojo.Basic.internal_static_BasicProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.pojo.Basic.internal_static_BasicProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.pojo.Basic.BasicProto.class, cn.pojo.Basic.BasicProto.Builder.class);
      }

      // Construct using cn.pojo.Basic.BasicProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        money_ = 0D;

        height_ = 0F;

        age_ = 0;

        distance_ = 0L;

        sex_ = false;

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.pojo.Basic.internal_static_BasicProto_descriptor;
      }

      public cn.pojo.Basic.BasicProto getDefaultInstanceForType() {
        return cn.pojo.Basic.BasicProto.getDefaultInstance();
      }

      public cn.pojo.Basic.BasicProto build() {
        cn.pojo.Basic.BasicProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.pojo.Basic.BasicProto buildPartial() {
        cn.pojo.Basic.BasicProto result = new cn.pojo.Basic.BasicProto(this);
        result.money_ = money_;
        result.height_ = height_;
        result.age_ = age_;
        result.distance_ = distance_;
        result.sex_ = sex_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.pojo.Basic.BasicProto) {
          return mergeFrom((cn.pojo.Basic.BasicProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.pojo.Basic.BasicProto other) {
        if (other == cn.pojo.Basic.BasicProto.getDefaultInstance()) return this;
        if (other.getMoney() != 0D) {
          setMoney(other.getMoney());
        }
        if (other.getHeight() != 0F) {
          setHeight(other.getHeight());
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getDistance() != 0L) {
          setDistance(other.getDistance());
        }
        if (other.getSex() != false) {
          setSex(other.getSex());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.pojo.Basic.BasicProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.pojo.Basic.BasicProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double money_ ;
      /**
       * <code>double money = 1;</code>
       */
      public double getMoney() {
        return money_;
      }
      /**
       * <code>double money = 1;</code>
       */
      public Builder setMoney(double value) {
        
        money_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double money = 1;</code>
       */
      public Builder clearMoney() {
        
        money_ = 0D;
        onChanged();
        return this;
      }

      private float height_ ;
      /**
       * <code>float height = 2;</code>
       */
      public float getHeight() {
        return height_;
      }
      /**
       * <code>float height = 2;</code>
       */
      public Builder setHeight(float value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float height = 2;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0F;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private long distance_ ;
      /**
       * <pre>
       * long
       * </pre>
       *
       * <code>int64 distance = 4;</code>
       */
      public long getDistance() {
        return distance_;
      }
      /**
       * <pre>
       * long
       * </pre>
       *
       * <code>int64 distance = 4;</code>
       */
      public Builder setDistance(long value) {
        
        distance_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * long
       * </pre>
       *
       * <code>int64 distance = 4;</code>
       */
      public Builder clearDistance() {
        
        distance_ = 0L;
        onChanged();
        return this;
      }

      private boolean sex_ ;
      /**
       * <pre>
       * boolean
       * </pre>
       *
       * <code>bool sex = 5;</code>
       */
      public boolean getSex() {
        return sex_;
      }
      /**
       * <pre>
       * boolean
       * </pre>
       *
       * <code>bool sex = 5;</code>
       */
      public Builder setSex(boolean value) {
        
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * boolean
       * </pre>
       *
       * <code>bool sex = 5;</code>
       */
      public Builder clearSex() {
        
        sex_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 6;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 6;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 6;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 6;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BasicProto)
    }

    // @@protoc_insertion_point(class_scope:BasicProto)
    private static final cn.pojo.Basic.BasicProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.pojo.Basic.BasicProto();
    }

    public static cn.pojo.Basic.BasicProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BasicProto>
        PARSER = new com.google.protobuf.AbstractParser<BasicProto>() {
      public BasicProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BasicProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BasicProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BasicProto> getParserForType() {
      return PARSER;
    }

    public cn.pojo.Basic.BasicProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BasicProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BasicProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013basic.proto\"e\n\nBasicProto\022\r\n\005money\030\001 \001" +
      "(\001\022\016\n\006height\030\002 \001(\002\022\013\n\003age\030\003 \001(\005\022\020\n\010dista" +
      "nce\030\004 \001(\003\022\013\n\003sex\030\005 \001(\010\022\014\n\004name\030\006 \001(\tB\020\n\007" +
      "cn.pojoB\005Basicb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BasicProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BasicProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BasicProto_descriptor,
        new java.lang.String[] { "Money", "Height", "Age", "Distance", "Sex", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
