// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum.proto

package cn.pojo;

public final class Enum {
  private Enum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EnumProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EnumProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.EnumProto.Seasons seasons = 7;</code>
     */
    int getSeasonsValue();
    /**
     * <code>.EnumProto.Seasons seasons = 7;</code>
     */
    cn.pojo.Enum.EnumProto.Seasons getSeasons();

    /**
     * <code>.EnumProto.Weather weather = 8;</code>
     */
    int getWeatherValue();
    /**
     * <code>.EnumProto.Weather weather = 8;</code>
     */
    cn.pojo.Enum.EnumProto.Weather getWeather();
  }
  /**
   * Protobuf type {@code EnumProto}
   */
  public  static final class EnumProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EnumProto)
      EnumProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EnumProto.newBuilder() to construct.
    private EnumProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnumProto() {
      seasons_ = 0;
      weather_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EnumProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              seasons_ = rawValue;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              weather_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.pojo.Enum.internal_static_EnumProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.pojo.Enum.internal_static_EnumProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.pojo.Enum.EnumProto.class, cn.pojo.Enum.EnumProto.Builder.class);
    }

    /**
     * Protobuf enum {@code EnumProto.Seasons}
     */
    public enum Seasons
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SPRING = 0;</code>
       */
      SPRING(0),
      /**
       * <code>SUMMER = 1;</code>
       */
      SUMMER(1),
      /**
       * <code>AUTUMN = 2;</code>
       */
      AUTUMN(2),
      /**
       * <code>WINTER = 3;</code>
       */
      WINTER(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SPRING = 0;</code>
       */
      public static final int SPRING_VALUE = 0;
      /**
       * <code>SUMMER = 1;</code>
       */
      public static final int SUMMER_VALUE = 1;
      /**
       * <code>AUTUMN = 2;</code>
       */
      public static final int AUTUMN_VALUE = 2;
      /**
       * <code>WINTER = 3;</code>
       */
      public static final int WINTER_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Seasons valueOf(int value) {
        return forNumber(value);
      }

      public static Seasons forNumber(int value) {
        switch (value) {
          case 0: return SPRING;
          case 1: return SUMMER;
          case 2: return AUTUMN;
          case 3: return WINTER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Seasons>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Seasons> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Seasons>() {
              public Seasons findValueByNumber(int number) {
                return Seasons.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cn.pojo.Enum.EnumProto.getDescriptor().getEnumTypes().get(0);
      }

      private static final Seasons[] VALUES = values();

      public static Seasons valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Seasons(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:EnumProto.Seasons)
    }

    /**
     * Protobuf enum {@code EnumProto.Weather}
     */
    public enum Weather
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RAIN = 0;</code>
       */
      RAIN(0),
      /**
       * <code>CLOUDY = 1;</code>
       */
      CLOUDY(1),
      /**
       * <code>SUNNY = 2;</code>
       */
      SUNNY(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>RAIN = 0;</code>
       */
      public static final int RAIN_VALUE = 0;
      /**
       * <code>CLOUDY = 1;</code>
       */
      public static final int CLOUDY_VALUE = 1;
      /**
       * <code>SUNNY = 2;</code>
       */
      public static final int SUNNY_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Weather valueOf(int value) {
        return forNumber(value);
      }

      public static Weather forNumber(int value) {
        switch (value) {
          case 0: return RAIN;
          case 1: return CLOUDY;
          case 2: return SUNNY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Weather>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Weather> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Weather>() {
              public Weather findValueByNumber(int number) {
                return Weather.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cn.pojo.Enum.EnumProto.getDescriptor().getEnumTypes().get(1);
      }

      private static final Weather[] VALUES = values();

      public static Weather valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Weather(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:EnumProto.Weather)
    }

    public static final int SEASONS_FIELD_NUMBER = 7;
    private int seasons_;
    /**
     * <code>.EnumProto.Seasons seasons = 7;</code>
     */
    public int getSeasonsValue() {
      return seasons_;
    }
    /**
     * <code>.EnumProto.Seasons seasons = 7;</code>
     */
    public cn.pojo.Enum.EnumProto.Seasons getSeasons() {
      cn.pojo.Enum.EnumProto.Seasons result = cn.pojo.Enum.EnumProto.Seasons.valueOf(seasons_);
      return result == null ? cn.pojo.Enum.EnumProto.Seasons.UNRECOGNIZED : result;
    }

    public static final int WEATHER_FIELD_NUMBER = 8;
    private int weather_;
    /**
     * <code>.EnumProto.Weather weather = 8;</code>
     */
    public int getWeatherValue() {
      return weather_;
    }
    /**
     * <code>.EnumProto.Weather weather = 8;</code>
     */
    public cn.pojo.Enum.EnumProto.Weather getWeather() {
      cn.pojo.Enum.EnumProto.Weather result = cn.pojo.Enum.EnumProto.Weather.valueOf(weather_);
      return result == null ? cn.pojo.Enum.EnumProto.Weather.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (seasons_ != cn.pojo.Enum.EnumProto.Seasons.SPRING.getNumber()) {
        output.writeEnum(7, seasons_);
      }
      if (weather_ != cn.pojo.Enum.EnumProto.Weather.RAIN.getNumber()) {
        output.writeEnum(8, weather_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (seasons_ != cn.pojo.Enum.EnumProto.Seasons.SPRING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, seasons_);
      }
      if (weather_ != cn.pojo.Enum.EnumProto.Weather.RAIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, weather_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.pojo.Enum.EnumProto)) {
        return super.equals(obj);
      }
      cn.pojo.Enum.EnumProto other = (cn.pojo.Enum.EnumProto) obj;

      boolean result = true;
      result = result && seasons_ == other.seasons_;
      result = result && weather_ == other.weather_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEASONS_FIELD_NUMBER;
      hash = (53 * hash) + seasons_;
      hash = (37 * hash) + WEATHER_FIELD_NUMBER;
      hash = (53 * hash) + weather_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.pojo.Enum.EnumProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Enum.EnumProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Enum.EnumProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Enum.EnumProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Enum.EnumProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Enum.EnumProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Enum.EnumProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.pojo.Enum.EnumProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.pojo.Enum.EnumProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.pojo.Enum.EnumProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.pojo.Enum.EnumProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.pojo.Enum.EnumProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.pojo.Enum.EnumProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EnumProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EnumProto)
        cn.pojo.Enum.EnumProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.pojo.Enum.internal_static_EnumProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.pojo.Enum.internal_static_EnumProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.pojo.Enum.EnumProto.class, cn.pojo.Enum.EnumProto.Builder.class);
      }

      // Construct using cn.pojo.Enum.EnumProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        seasons_ = 0;

        weather_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.pojo.Enum.internal_static_EnumProto_descriptor;
      }

      public cn.pojo.Enum.EnumProto getDefaultInstanceForType() {
        return cn.pojo.Enum.EnumProto.getDefaultInstance();
      }

      public cn.pojo.Enum.EnumProto build() {
        cn.pojo.Enum.EnumProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.pojo.Enum.EnumProto buildPartial() {
        cn.pojo.Enum.EnumProto result = new cn.pojo.Enum.EnumProto(this);
        result.seasons_ = seasons_;
        result.weather_ = weather_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.pojo.Enum.EnumProto) {
          return mergeFrom((cn.pojo.Enum.EnumProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.pojo.Enum.EnumProto other) {
        if (other == cn.pojo.Enum.EnumProto.getDefaultInstance()) return this;
        if (other.seasons_ != 0) {
          setSeasonsValue(other.getSeasonsValue());
        }
        if (other.weather_ != 0) {
          setWeatherValue(other.getWeatherValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.pojo.Enum.EnumProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.pojo.Enum.EnumProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int seasons_ = 0;
      /**
       * <code>.EnumProto.Seasons seasons = 7;</code>
       */
      public int getSeasonsValue() {
        return seasons_;
      }
      /**
       * <code>.EnumProto.Seasons seasons = 7;</code>
       */
      public Builder setSeasonsValue(int value) {
        seasons_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.EnumProto.Seasons seasons = 7;</code>
       */
      public cn.pojo.Enum.EnumProto.Seasons getSeasons() {
        cn.pojo.Enum.EnumProto.Seasons result = cn.pojo.Enum.EnumProto.Seasons.valueOf(seasons_);
        return result == null ? cn.pojo.Enum.EnumProto.Seasons.UNRECOGNIZED : result;
      }
      /**
       * <code>.EnumProto.Seasons seasons = 7;</code>
       */
      public Builder setSeasons(cn.pojo.Enum.EnumProto.Seasons value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        seasons_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.EnumProto.Seasons seasons = 7;</code>
       */
      public Builder clearSeasons() {
        
        seasons_ = 0;
        onChanged();
        return this;
      }

      private int weather_ = 0;
      /**
       * <code>.EnumProto.Weather weather = 8;</code>
       */
      public int getWeatherValue() {
        return weather_;
      }
      /**
       * <code>.EnumProto.Weather weather = 8;</code>
       */
      public Builder setWeatherValue(int value) {
        weather_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.EnumProto.Weather weather = 8;</code>
       */
      public cn.pojo.Enum.EnumProto.Weather getWeather() {
        cn.pojo.Enum.EnumProto.Weather result = cn.pojo.Enum.EnumProto.Weather.valueOf(weather_);
        return result == null ? cn.pojo.Enum.EnumProto.Weather.UNRECOGNIZED : result;
      }
      /**
       * <code>.EnumProto.Weather weather = 8;</code>
       */
      public Builder setWeather(cn.pojo.Enum.EnumProto.Weather value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        weather_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.EnumProto.Weather weather = 8;</code>
       */
      public Builder clearWeather() {
        
        weather_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EnumProto)
    }

    // @@protoc_insertion_point(class_scope:EnumProto)
    private static final cn.pojo.Enum.EnumProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.pojo.Enum.EnumProto();
    }

    public static cn.pojo.Enum.EnumProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnumProto>
        PARSER = new com.google.protobuf.AbstractParser<EnumProto>() {
      public EnumProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnumProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EnumProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnumProto> getParserForType() {
      return PARSER;
    }

    public cn.pojo.Enum.EnumProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnumProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnumProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nenum.proto\"\274\001\n\tEnumProto\022#\n\007seasons\030\007 " +
      "\001(\0162\022.EnumProto.Seasons\022#\n\007weather\030\010 \001(\016" +
      "2\022.EnumProto.Weather\"9\n\007Seasons\022\n\n\006SPRIN" +
      "G\020\000\022\n\n\006SUMMER\020\001\022\n\n\006AUTUMN\020\002\022\n\n\006WINTER\020\003\"" +
      "*\n\007Weather\022\010\n\004RAIN\020\000\022\n\n\006CLOUDY\020\001\022\t\n\005SUNN" +
      "Y\020\002B\017\n\007cn.pojoB\004Enumb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EnumProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EnumProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnumProto_descriptor,
        new java.lang.String[] { "Seasons", "Weather", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
