// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: importing.proto

package cn.pojo;

public final class Importing {
  private Importing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImportProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImportProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.BasicProto basic = 9;</code>
     */
    boolean hasBasic();
    /**
     * <code>.BasicProto basic = 9;</code>
     */
    cn.pojo.Basic.BasicProto getBasic();
    /**
     * <code>.BasicProto basic = 9;</code>
     */
    cn.pojo.Basic.BasicProtoOrBuilder getBasicOrBuilder();

    /**
     * <code>.EnumProto enumProto = 10;</code>
     */
    boolean hasEnumProto();
    /**
     * <code>.EnumProto enumProto = 10;</code>
     */
    cn.pojo.Enum.EnumProto getEnumProto();
    /**
     * <code>.EnumProto enumProto = 10;</code>
     */
    cn.pojo.Enum.EnumProtoOrBuilder getEnumProtoOrBuilder();
  }
  /**
   * Protobuf type {@code ImportProto}
   */
  public  static final class ImportProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImportProto)
      ImportProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImportProto.newBuilder() to construct.
    private ImportProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImportProto() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImportProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 74: {
              cn.pojo.Basic.BasicProto.Builder subBuilder = null;
              if (basic_ != null) {
                subBuilder = basic_.toBuilder();
              }
              basic_ = input.readMessage(cn.pojo.Basic.BasicProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(basic_);
                basic_ = subBuilder.buildPartial();
              }

              break;
            }
            case 82: {
              cn.pojo.Enum.EnumProto.Builder subBuilder = null;
              if (enumProto_ != null) {
                subBuilder = enumProto_.toBuilder();
              }
              enumProto_ = input.readMessage(cn.pojo.Enum.EnumProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(enumProto_);
                enumProto_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.pojo.Importing.internal_static_ImportProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.pojo.Importing.internal_static_ImportProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.pojo.Importing.ImportProto.class, cn.pojo.Importing.ImportProto.Builder.class);
    }

    public static final int BASIC_FIELD_NUMBER = 9;
    private cn.pojo.Basic.BasicProto basic_;
    /**
     * <code>.BasicProto basic = 9;</code>
     */
    public boolean hasBasic() {
      return basic_ != null;
    }
    /**
     * <code>.BasicProto basic = 9;</code>
     */
    public cn.pojo.Basic.BasicProto getBasic() {
      return basic_ == null ? cn.pojo.Basic.BasicProto.getDefaultInstance() : basic_;
    }
    /**
     * <code>.BasicProto basic = 9;</code>
     */
    public cn.pojo.Basic.BasicProtoOrBuilder getBasicOrBuilder() {
      return getBasic();
    }

    public static final int ENUMPROTO_FIELD_NUMBER = 10;
    private cn.pojo.Enum.EnumProto enumProto_;
    /**
     * <code>.EnumProto enumProto = 10;</code>
     */
    public boolean hasEnumProto() {
      return enumProto_ != null;
    }
    /**
     * <code>.EnumProto enumProto = 10;</code>
     */
    public cn.pojo.Enum.EnumProto getEnumProto() {
      return enumProto_ == null ? cn.pojo.Enum.EnumProto.getDefaultInstance() : enumProto_;
    }
    /**
     * <code>.EnumProto enumProto = 10;</code>
     */
    public cn.pojo.Enum.EnumProtoOrBuilder getEnumProtoOrBuilder() {
      return getEnumProto();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (basic_ != null) {
        output.writeMessage(9, getBasic());
      }
      if (enumProto_ != null) {
        output.writeMessage(10, getEnumProto());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (basic_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getBasic());
      }
      if (enumProto_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getEnumProto());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.pojo.Importing.ImportProto)) {
        return super.equals(obj);
      }
      cn.pojo.Importing.ImportProto other = (cn.pojo.Importing.ImportProto) obj;

      boolean result = true;
      result = result && (hasBasic() == other.hasBasic());
      if (hasBasic()) {
        result = result && getBasic()
            .equals(other.getBasic());
      }
      result = result && (hasEnumProto() == other.hasEnumProto());
      if (hasEnumProto()) {
        result = result && getEnumProto()
            .equals(other.getEnumProto());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBasic()) {
        hash = (37 * hash) + BASIC_FIELD_NUMBER;
        hash = (53 * hash) + getBasic().hashCode();
      }
      if (hasEnumProto()) {
        hash = (37 * hash) + ENUMPROTO_FIELD_NUMBER;
        hash = (53 * hash) + getEnumProto().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.pojo.Importing.ImportProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Importing.ImportProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Importing.ImportProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Importing.ImportProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Importing.ImportProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Importing.ImportProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Importing.ImportProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.pojo.Importing.ImportProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.pojo.Importing.ImportProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.pojo.Importing.ImportProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.pojo.Importing.ImportProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.pojo.Importing.ImportProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.pojo.Importing.ImportProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ImportProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImportProto)
        cn.pojo.Importing.ImportProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.pojo.Importing.internal_static_ImportProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.pojo.Importing.internal_static_ImportProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.pojo.Importing.ImportProto.class, cn.pojo.Importing.ImportProto.Builder.class);
      }

      // Construct using cn.pojo.Importing.ImportProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (basicBuilder_ == null) {
          basic_ = null;
        } else {
          basic_ = null;
          basicBuilder_ = null;
        }
        if (enumProtoBuilder_ == null) {
          enumProto_ = null;
        } else {
          enumProto_ = null;
          enumProtoBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.pojo.Importing.internal_static_ImportProto_descriptor;
      }

      public cn.pojo.Importing.ImportProto getDefaultInstanceForType() {
        return cn.pojo.Importing.ImportProto.getDefaultInstance();
      }

      public cn.pojo.Importing.ImportProto build() {
        cn.pojo.Importing.ImportProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.pojo.Importing.ImportProto buildPartial() {
        cn.pojo.Importing.ImportProto result = new cn.pojo.Importing.ImportProto(this);
        if (basicBuilder_ == null) {
          result.basic_ = basic_;
        } else {
          result.basic_ = basicBuilder_.build();
        }
        if (enumProtoBuilder_ == null) {
          result.enumProto_ = enumProto_;
        } else {
          result.enumProto_ = enumProtoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.pojo.Importing.ImportProto) {
          return mergeFrom((cn.pojo.Importing.ImportProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.pojo.Importing.ImportProto other) {
        if (other == cn.pojo.Importing.ImportProto.getDefaultInstance()) return this;
        if (other.hasBasic()) {
          mergeBasic(other.getBasic());
        }
        if (other.hasEnumProto()) {
          mergeEnumProto(other.getEnumProto());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.pojo.Importing.ImportProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.pojo.Importing.ImportProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private cn.pojo.Basic.BasicProto basic_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.pojo.Basic.BasicProto, cn.pojo.Basic.BasicProto.Builder, cn.pojo.Basic.BasicProtoOrBuilder> basicBuilder_;
      /**
       * <code>.BasicProto basic = 9;</code>
       */
      public boolean hasBasic() {
        return basicBuilder_ != null || basic_ != null;
      }
      /**
       * <code>.BasicProto basic = 9;</code>
       */
      public cn.pojo.Basic.BasicProto getBasic() {
        if (basicBuilder_ == null) {
          return basic_ == null ? cn.pojo.Basic.BasicProto.getDefaultInstance() : basic_;
        } else {
          return basicBuilder_.getMessage();
        }
      }
      /**
       * <code>.BasicProto basic = 9;</code>
       */
      public Builder setBasic(cn.pojo.Basic.BasicProto value) {
        if (basicBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          basic_ = value;
          onChanged();
        } else {
          basicBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BasicProto basic = 9;</code>
       */
      public Builder setBasic(
          cn.pojo.Basic.BasicProto.Builder builderForValue) {
        if (basicBuilder_ == null) {
          basic_ = builderForValue.build();
          onChanged();
        } else {
          basicBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BasicProto basic = 9;</code>
       */
      public Builder mergeBasic(cn.pojo.Basic.BasicProto value) {
        if (basicBuilder_ == null) {
          if (basic_ != null) {
            basic_ =
              cn.pojo.Basic.BasicProto.newBuilder(basic_).mergeFrom(value).buildPartial();
          } else {
            basic_ = value;
          }
          onChanged();
        } else {
          basicBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BasicProto basic = 9;</code>
       */
      public Builder clearBasic() {
        if (basicBuilder_ == null) {
          basic_ = null;
          onChanged();
        } else {
          basic_ = null;
          basicBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BasicProto basic = 9;</code>
       */
      public cn.pojo.Basic.BasicProto.Builder getBasicBuilder() {
        
        onChanged();
        return getBasicFieldBuilder().getBuilder();
      }
      /**
       * <code>.BasicProto basic = 9;</code>
       */
      public cn.pojo.Basic.BasicProtoOrBuilder getBasicOrBuilder() {
        if (basicBuilder_ != null) {
          return basicBuilder_.getMessageOrBuilder();
        } else {
          return basic_ == null ?
              cn.pojo.Basic.BasicProto.getDefaultInstance() : basic_;
        }
      }
      /**
       * <code>.BasicProto basic = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.pojo.Basic.BasicProto, cn.pojo.Basic.BasicProto.Builder, cn.pojo.Basic.BasicProtoOrBuilder> 
          getBasicFieldBuilder() {
        if (basicBuilder_ == null) {
          basicBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.pojo.Basic.BasicProto, cn.pojo.Basic.BasicProto.Builder, cn.pojo.Basic.BasicProtoOrBuilder>(
                  getBasic(),
                  getParentForChildren(),
                  isClean());
          basic_ = null;
        }
        return basicBuilder_;
      }

      private cn.pojo.Enum.EnumProto enumProto_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.pojo.Enum.EnumProto, cn.pojo.Enum.EnumProto.Builder, cn.pojo.Enum.EnumProtoOrBuilder> enumProtoBuilder_;
      /**
       * <code>.EnumProto enumProto = 10;</code>
       */
      public boolean hasEnumProto() {
        return enumProtoBuilder_ != null || enumProto_ != null;
      }
      /**
       * <code>.EnumProto enumProto = 10;</code>
       */
      public cn.pojo.Enum.EnumProto getEnumProto() {
        if (enumProtoBuilder_ == null) {
          return enumProto_ == null ? cn.pojo.Enum.EnumProto.getDefaultInstance() : enumProto_;
        } else {
          return enumProtoBuilder_.getMessage();
        }
      }
      /**
       * <code>.EnumProto enumProto = 10;</code>
       */
      public Builder setEnumProto(cn.pojo.Enum.EnumProto value) {
        if (enumProtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          enumProto_ = value;
          onChanged();
        } else {
          enumProtoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.EnumProto enumProto = 10;</code>
       */
      public Builder setEnumProto(
          cn.pojo.Enum.EnumProto.Builder builderForValue) {
        if (enumProtoBuilder_ == null) {
          enumProto_ = builderForValue.build();
          onChanged();
        } else {
          enumProtoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.EnumProto enumProto = 10;</code>
       */
      public Builder mergeEnumProto(cn.pojo.Enum.EnumProto value) {
        if (enumProtoBuilder_ == null) {
          if (enumProto_ != null) {
            enumProto_ =
              cn.pojo.Enum.EnumProto.newBuilder(enumProto_).mergeFrom(value).buildPartial();
          } else {
            enumProto_ = value;
          }
          onChanged();
        } else {
          enumProtoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.EnumProto enumProto = 10;</code>
       */
      public Builder clearEnumProto() {
        if (enumProtoBuilder_ == null) {
          enumProto_ = null;
          onChanged();
        } else {
          enumProto_ = null;
          enumProtoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.EnumProto enumProto = 10;</code>
       */
      public cn.pojo.Enum.EnumProto.Builder getEnumProtoBuilder() {
        
        onChanged();
        return getEnumProtoFieldBuilder().getBuilder();
      }
      /**
       * <code>.EnumProto enumProto = 10;</code>
       */
      public cn.pojo.Enum.EnumProtoOrBuilder getEnumProtoOrBuilder() {
        if (enumProtoBuilder_ != null) {
          return enumProtoBuilder_.getMessageOrBuilder();
        } else {
          return enumProto_ == null ?
              cn.pojo.Enum.EnumProto.getDefaultInstance() : enumProto_;
        }
      }
      /**
       * <code>.EnumProto enumProto = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.pojo.Enum.EnumProto, cn.pojo.Enum.EnumProto.Builder, cn.pojo.Enum.EnumProtoOrBuilder> 
          getEnumProtoFieldBuilder() {
        if (enumProtoBuilder_ == null) {
          enumProtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.pojo.Enum.EnumProto, cn.pojo.Enum.EnumProto.Builder, cn.pojo.Enum.EnumProtoOrBuilder>(
                  getEnumProto(),
                  getParentForChildren(),
                  isClean());
          enumProto_ = null;
        }
        return enumProtoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImportProto)
    }

    // @@protoc_insertion_point(class_scope:ImportProto)
    private static final cn.pojo.Importing.ImportProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.pojo.Importing.ImportProto();
    }

    public static cn.pojo.Importing.ImportProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImportProto>
        PARSER = new com.google.protobuf.AbstractParser<ImportProto>() {
      public ImportProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImportProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImportProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImportProto> getParserForType() {
      return PARSER;
    }

    public cn.pojo.Importing.ImportProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImportProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImportProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017importing.proto\032\013basic.proto\032\nenum.pro" +
      "to\"H\n\013ImportProto\022\032\n\005basic\030\t \001(\0132\013.Basic" +
      "Proto\022\035\n\tenumProto\030\n \001(\0132\n.EnumProtoB\024\n\007" +
      "cn.pojoB\tImportingb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.pojo.Basic.getDescriptor(),
          cn.pojo.Enum.getDescriptor(),
        }, assigner);
    internal_static_ImportProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImportProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImportProto_descriptor,
        new java.lang.String[] { "Basic", "EnumProto", });
    cn.pojo.Basic.getDescriptor();
    cn.pojo.Enum.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
