// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nest.proto

package cn.pojo;

public final class Nest {
  private Nest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NestProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NestProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.NestProto.Animal.Dog dog = 6;</code>
     */
    boolean hasDog();
    /**
     * <code>.NestProto.Animal.Dog dog = 6;</code>
     */
    cn.pojo.Nest.NestProto.Animal.Dog getDog();
    /**
     * <code>.NestProto.Animal.Dog dog = 6;</code>
     */
    cn.pojo.Nest.NestProto.Animal.DogOrBuilder getDogOrBuilder();

    /**
     * <code>.NestProto.Dinosaur dinosaur = 7;</code>
     */
    boolean hasDinosaur();
    /**
     * <code>.NestProto.Dinosaur dinosaur = 7;</code>
     */
    cn.pojo.Nest.NestProto.Dinosaur getDinosaur();
    /**
     * <code>.NestProto.Dinosaur dinosaur = 7;</code>
     */
    cn.pojo.Nest.NestProto.DinosaurOrBuilder getDinosaurOrBuilder();
  }
  /**
   * Protobuf type {@code NestProto}
   */
  public  static final class NestProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NestProto)
      NestProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NestProto.newBuilder() to construct.
    private NestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NestProto() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 50: {
              cn.pojo.Nest.NestProto.Animal.Dog.Builder subBuilder = null;
              if (dog_ != null) {
                subBuilder = dog_.toBuilder();
              }
              dog_ = input.readMessage(cn.pojo.Nest.NestProto.Animal.Dog.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dog_);
                dog_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              cn.pojo.Nest.NestProto.Dinosaur.Builder subBuilder = null;
              if (dinosaur_ != null) {
                subBuilder = dinosaur_.toBuilder();
              }
              dinosaur_ = input.readMessage(cn.pojo.Nest.NestProto.Dinosaur.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dinosaur_);
                dinosaur_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.pojo.Nest.internal_static_NestProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.pojo.Nest.internal_static_NestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.pojo.Nest.NestProto.class, cn.pojo.Nest.NestProto.Builder.class);
    }

    public interface AnimalOrBuilder extends
        // @@protoc_insertion_point(interface_extends:NestProto.Animal)
        com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code NestProto.Animal}
     */
    public  static final class Animal extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:NestProto.Animal)
        AnimalOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Animal.newBuilder() to construct.
      private Animal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Animal() {
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Animal(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.pojo.Nest.internal_static_NestProto_Animal_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.pojo.Nest.internal_static_NestProto_Animal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.pojo.Nest.NestProto.Animal.class, cn.pojo.Nest.NestProto.Animal.Builder.class);
      }

      public interface DogOrBuilder extends
          // @@protoc_insertion_point(interface_extends:NestProto.Animal.Dog)
          com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string name = 1;</code>
         */
        java.lang.String getName();
        /**
         * <code>string name = 1;</code>
         */
        com.google.protobuf.ByteString
            getNameBytes();

        /**
         * <code>int32 age = 2;</code>
         */
        int getAge();
      }
      /**
       * Protobuf type {@code NestProto.Animal.Dog}
       */
      public  static final class Dog extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:NestProto.Animal.Dog)
          DogOrBuilder {
      private static final long serialVersionUID = 0L;
        // Use Dog.newBuilder() to construct.
        private Dog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
          super(builder);
        }
        private Dog() {
          name_ = "";
          age_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
          return this.unknownFields;
        }
        private Dog(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          this();
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          int mutable_bitField0_ = 0;
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownFieldProto3(
                      input, unknownFields, extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  java.lang.String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                case 16: {

                  age_ = input.readInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
          } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
          }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return cn.pojo.Nest.internal_static_NestProto_Animal_Dog_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return cn.pojo.Nest.internal_static_NestProto_Animal_Dog_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  cn.pojo.Nest.NestProto.Animal.Dog.class, cn.pojo.Nest.NestProto.Animal.Dog.Builder.class);
        }

        public static final int NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object name_;
        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        public static final int AGE_FIELD_NUMBER = 2;
        private int age_;
        /**
         * <code>int32 age = 2;</code>
         */
        public int getAge() {
          return age_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return true;
          if (isInitialized == 0) return false;

          memoizedIsInitialized = 1;
          return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          if (!getNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
          }
          if (age_ != 0) {
            output.writeInt32(2, age_);
          }
          unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
          int size = memoizedSize;
          if (size != -1) return size;

          size = 0;
          if (!getNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
          }
          if (age_ != 0) {
            size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(2, age_);
          }
          size += unknownFields.getSerializedSize();
          memoizedSize = size;
          return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
          if (obj == this) {
           return true;
          }
          if (!(obj instanceof cn.pojo.Nest.NestProto.Animal.Dog)) {
            return super.equals(obj);
          }
          cn.pojo.Nest.NestProto.Animal.Dog other = (cn.pojo.Nest.NestProto.Animal.Dog) obj;

          boolean result = true;
          result = result && getName()
              .equals(other.getName());
          result = result && (getAge()
              == other.getAge());
          result = result && unknownFields.equals(other.unknownFields);
          return result;
        }

        @java.lang.Override
        public int hashCode() {
          if (memoizedHashCode != 0) {
            return memoizedHashCode;
          }
          int hash = 41;
          hash = (19 * hash) + getDescriptor().hashCode();
          hash = (37 * hash) + NAME_FIELD_NUMBER;
          hash = (53 * hash) + getName().hashCode();
          hash = (37 * hash) + AGE_FIELD_NUMBER;
          hash = (53 * hash) + getAge();
          hash = (29 * hash) + unknownFields.hashCode();
          memoizedHashCode = hash;
          return hash;
        }

        public static cn.pojo.Nest.NestProto.Animal.Dog parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static cn.pojo.Nest.NestProto.Animal.Dog parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static cn.pojo.Nest.NestProto.Animal.Dog parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static cn.pojo.Nest.NestProto.Animal.Dog parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static cn.pojo.Nest.NestProto.Animal.Dog parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static cn.pojo.Nest.NestProto.Animal.Dog parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static cn.pojo.Nest.NestProto.Animal.Dog parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static cn.pojo.Nest.NestProto.Animal.Dog parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static cn.pojo.Nest.NestProto.Animal.Dog parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
        }
        public static cn.pojo.Nest.NestProto.Animal.Dog parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static cn.pojo.Nest.NestProto.Animal.Dog parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static cn.pojo.Nest.NestProto.Animal.Dog parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
          return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(cn.pojo.Nest.NestProto.Animal.Dog prototype) {
          return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
          return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        /**
         * Protobuf type {@code NestProto.Animal.Dog}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:NestProto.Animal.Dog)
            cn.pojo.Nest.NestProto.Animal.DogOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return cn.pojo.Nest.internal_static_NestProto_Animal_Dog_descriptor;
          }

          protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return cn.pojo.Nest.internal_static_NestProto_Animal_Dog_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    cn.pojo.Nest.NestProto.Animal.Dog.class, cn.pojo.Nest.NestProto.Animal.Dog.Builder.class);
          }

          // Construct using cn.pojo.Nest.NestProto.Animal.Dog.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }

          private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
          }
          public Builder clear() {
            super.clear();
            name_ = "";

            age_ = 0;

            return this;
          }

          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return cn.pojo.Nest.internal_static_NestProto_Animal_Dog_descriptor;
          }

          public cn.pojo.Nest.NestProto.Animal.Dog getDefaultInstanceForType() {
            return cn.pojo.Nest.NestProto.Animal.Dog.getDefaultInstance();
          }

          public cn.pojo.Nest.NestProto.Animal.Dog build() {
            cn.pojo.Nest.NestProto.Animal.Dog result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          public cn.pojo.Nest.NestProto.Animal.Dog buildPartial() {
            cn.pojo.Nest.NestProto.Animal.Dog result = new cn.pojo.Nest.NestProto.Animal.Dog(this);
            result.name_ = name_;
            result.age_ = age_;
            onBuilt();
            return result;
          }

          public Builder clone() {
            return (Builder) super.clone();
          }
          public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return (Builder) super.setField(field, value);
          }
          public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
          }
          public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
          }
          public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
          }
          public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
          }
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cn.pojo.Nest.NestProto.Animal.Dog) {
              return mergeFrom((cn.pojo.Nest.NestProto.Animal.Dog)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }

          public Builder mergeFrom(cn.pojo.Nest.NestProto.Animal.Dog other) {
            if (other == cn.pojo.Nest.NestProto.Animal.Dog.getDefaultInstance()) return this;
            if (!other.getName().isEmpty()) {
              name_ = other.name_;
              onChanged();
            }
            if (other.getAge() != 0) {
              setAge(other.getAge());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
          }

          public final boolean isInitialized() {
            return true;
          }

          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            cn.pojo.Nest.NestProto.Animal.Dog parsedMessage = null;
            try {
              parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              parsedMessage = (cn.pojo.Nest.NestProto.Animal.Dog) e.getUnfinishedMessage();
              throw e.unwrapIOException();
            } finally {
              if (parsedMessage != null) {
                mergeFrom(parsedMessage);
              }
            }
            return this;
          }

          private java.lang.Object name_ = "";
          /**
           * <code>string name = 1;</code>
           */
          public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (!(ref instanceof java.lang.String)) {
              com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
              java.lang.String s = bs.toStringUtf8();
              name_ = s;
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>string name = 1;</code>
           */
          public com.google.protobuf.ByteString
              getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              name_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>string name = 1;</code>
           */
          public Builder setName(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  
            name_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>string name = 1;</code>
           */
          public Builder clearName() {
            
            name_ = getDefaultInstance().getName();
            onChanged();
            return this;
          }
          /**
           * <code>string name = 1;</code>
           */
          public Builder setNameBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
            
            name_ = value;
            onChanged();
            return this;
          }

          private int age_ ;
          /**
           * <code>int32 age = 2;</code>
           */
          public int getAge() {
            return age_;
          }
          /**
           * <code>int32 age = 2;</code>
           */
          public Builder setAge(int value) {
            
            age_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>int32 age = 2;</code>
           */
          public Builder clearAge() {
            
            age_ = 0;
            onChanged();
            return this;
          }
          public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
          }

          public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
          }


          // @@protoc_insertion_point(builder_scope:NestProto.Animal.Dog)
        }

        // @@protoc_insertion_point(class_scope:NestProto.Animal.Dog)
        private static final cn.pojo.Nest.NestProto.Animal.Dog DEFAULT_INSTANCE;
        static {
          DEFAULT_INSTANCE = new cn.pojo.Nest.NestProto.Animal.Dog();
        }

        public static cn.pojo.Nest.NestProto.Animal.Dog getDefaultInstance() {
          return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Dog>
            PARSER = new com.google.protobuf.AbstractParser<Dog>() {
          public Dog parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Dog(input, extensionRegistry);
          }
        };

        public static com.google.protobuf.Parser<Dog> parser() {
          return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Dog> getParserForType() {
          return PARSER;
        }

        public cn.pojo.Nest.NestProto.Animal.Dog getDefaultInstanceForType() {
          return DEFAULT_INSTANCE;
        }

      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof cn.pojo.Nest.NestProto.Animal)) {
          return super.equals(obj);
        }
        cn.pojo.Nest.NestProto.Animal other = (cn.pojo.Nest.NestProto.Animal) obj;

        boolean result = true;
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static cn.pojo.Nest.NestProto.Animal parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.pojo.Nest.NestProto.Animal parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.pojo.Nest.NestProto.Animal parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.pojo.Nest.NestProto.Animal parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.pojo.Nest.NestProto.Animal parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.pojo.Nest.NestProto.Animal parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.pojo.Nest.NestProto.Animal parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cn.pojo.Nest.NestProto.Animal parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.pojo.Nest.NestProto.Animal parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static cn.pojo.Nest.NestProto.Animal parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.pojo.Nest.NestProto.Animal parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cn.pojo.Nest.NestProto.Animal parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(cn.pojo.Nest.NestProto.Animal prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code NestProto.Animal}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:NestProto.Animal)
          cn.pojo.Nest.NestProto.AnimalOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return cn.pojo.Nest.internal_static_NestProto_Animal_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return cn.pojo.Nest.internal_static_NestProto_Animal_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  cn.pojo.Nest.NestProto.Animal.class, cn.pojo.Nest.NestProto.Animal.Builder.class);
        }

        // Construct using cn.pojo.Nest.NestProto.Animal.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return cn.pojo.Nest.internal_static_NestProto_Animal_descriptor;
        }

        public cn.pojo.Nest.NestProto.Animal getDefaultInstanceForType() {
          return cn.pojo.Nest.NestProto.Animal.getDefaultInstance();
        }

        public cn.pojo.Nest.NestProto.Animal build() {
          cn.pojo.Nest.NestProto.Animal result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public cn.pojo.Nest.NestProto.Animal buildPartial() {
          cn.pojo.Nest.NestProto.Animal result = new cn.pojo.Nest.NestProto.Animal(this);
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof cn.pojo.Nest.NestProto.Animal) {
            return mergeFrom((cn.pojo.Nest.NestProto.Animal)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(cn.pojo.Nest.NestProto.Animal other) {
          if (other == cn.pojo.Nest.NestProto.Animal.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          cn.pojo.Nest.NestProto.Animal parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (cn.pojo.Nest.NestProto.Animal) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:NestProto.Animal)
      }

      // @@protoc_insertion_point(class_scope:NestProto.Animal)
      private static final cn.pojo.Nest.NestProto.Animal DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new cn.pojo.Nest.NestProto.Animal();
      }

      public static cn.pojo.Nest.NestProto.Animal getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Animal>
          PARSER = new com.google.protobuf.AbstractParser<Animal>() {
        public Animal parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Animal(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Animal> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Animal> getParserForType() {
        return PARSER;
      }

      public cn.pojo.Nest.NestProto.Animal getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface DinosaurOrBuilder extends
        // @@protoc_insertion_point(interface_extends:NestProto.Dinosaur)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>double weight = 4;</code>
       */
      double getWeight();

      /**
       * <code>string name = 5;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 5;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code NestProto.Dinosaur}
     */
    public  static final class Dinosaur extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:NestProto.Dinosaur)
        DinosaurOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Dinosaur.newBuilder() to construct.
      private Dinosaur(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Dinosaur() {
        weight_ = 0D;
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Dinosaur(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 33: {

                weight_ = input.readDouble();
                break;
              }
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.pojo.Nest.internal_static_NestProto_Dinosaur_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.pojo.Nest.internal_static_NestProto_Dinosaur_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.pojo.Nest.NestProto.Dinosaur.class, cn.pojo.Nest.NestProto.Dinosaur.Builder.class);
      }

      public static final int WEIGHT_FIELD_NUMBER = 4;
      private double weight_;
      /**
       * <code>double weight = 4;</code>
       */
      public double getWeight() {
        return weight_;
      }

      public static final int NAME_FIELD_NUMBER = 5;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 5;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (weight_ != 0D) {
          output.writeDouble(4, weight_);
        }
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (weight_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(4, weight_);
        }
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof cn.pojo.Nest.NestProto.Dinosaur)) {
          return super.equals(obj);
        }
        cn.pojo.Nest.NestProto.Dinosaur other = (cn.pojo.Nest.NestProto.Dinosaur) obj;

        boolean result = true;
        result = result && (
            java.lang.Double.doubleToLongBits(getWeight())
            == java.lang.Double.doubleToLongBits(
                other.getWeight()));
        result = result && getName()
            .equals(other.getName());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getWeight()));
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static cn.pojo.Nest.NestProto.Dinosaur parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.pojo.Nest.NestProto.Dinosaur parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.pojo.Nest.NestProto.Dinosaur parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.pojo.Nest.NestProto.Dinosaur parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.pojo.Nest.NestProto.Dinosaur parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.pojo.Nest.NestProto.Dinosaur parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.pojo.Nest.NestProto.Dinosaur parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cn.pojo.Nest.NestProto.Dinosaur parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.pojo.Nest.NestProto.Dinosaur parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static cn.pojo.Nest.NestProto.Dinosaur parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.pojo.Nest.NestProto.Dinosaur parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cn.pojo.Nest.NestProto.Dinosaur parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(cn.pojo.Nest.NestProto.Dinosaur prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code NestProto.Dinosaur}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:NestProto.Dinosaur)
          cn.pojo.Nest.NestProto.DinosaurOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return cn.pojo.Nest.internal_static_NestProto_Dinosaur_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return cn.pojo.Nest.internal_static_NestProto_Dinosaur_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  cn.pojo.Nest.NestProto.Dinosaur.class, cn.pojo.Nest.NestProto.Dinosaur.Builder.class);
        }

        // Construct using cn.pojo.Nest.NestProto.Dinosaur.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          weight_ = 0D;

          name_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return cn.pojo.Nest.internal_static_NestProto_Dinosaur_descriptor;
        }

        public cn.pojo.Nest.NestProto.Dinosaur getDefaultInstanceForType() {
          return cn.pojo.Nest.NestProto.Dinosaur.getDefaultInstance();
        }

        public cn.pojo.Nest.NestProto.Dinosaur build() {
          cn.pojo.Nest.NestProto.Dinosaur result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public cn.pojo.Nest.NestProto.Dinosaur buildPartial() {
          cn.pojo.Nest.NestProto.Dinosaur result = new cn.pojo.Nest.NestProto.Dinosaur(this);
          result.weight_ = weight_;
          result.name_ = name_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof cn.pojo.Nest.NestProto.Dinosaur) {
            return mergeFrom((cn.pojo.Nest.NestProto.Dinosaur)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(cn.pojo.Nest.NestProto.Dinosaur other) {
          if (other == cn.pojo.Nest.NestProto.Dinosaur.getDefaultInstance()) return this;
          if (other.getWeight() != 0D) {
            setWeight(other.getWeight());
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          cn.pojo.Nest.NestProto.Dinosaur parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (cn.pojo.Nest.NestProto.Dinosaur) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private double weight_ ;
        /**
         * <code>double weight = 4;</code>
         */
        public double getWeight() {
          return weight_;
        }
        /**
         * <code>double weight = 4;</code>
         */
        public Builder setWeight(double value) {
          
          weight_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double weight = 4;</code>
         */
        public Builder clearWeight() {
          
          weight_ = 0D;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 5;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 5;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 5;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 5;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 5;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:NestProto.Dinosaur)
      }

      // @@protoc_insertion_point(class_scope:NestProto.Dinosaur)
      private static final cn.pojo.Nest.NestProto.Dinosaur DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new cn.pojo.Nest.NestProto.Dinosaur();
      }

      public static cn.pojo.Nest.NestProto.Dinosaur getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Dinosaur>
          PARSER = new com.google.protobuf.AbstractParser<Dinosaur>() {
        public Dinosaur parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Dinosaur(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Dinosaur> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Dinosaur> getParserForType() {
        return PARSER;
      }

      public cn.pojo.Nest.NestProto.Dinosaur getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int DOG_FIELD_NUMBER = 6;
    private cn.pojo.Nest.NestProto.Animal.Dog dog_;
    /**
     * <code>.NestProto.Animal.Dog dog = 6;</code>
     */
    public boolean hasDog() {
      return dog_ != null;
    }
    /**
     * <code>.NestProto.Animal.Dog dog = 6;</code>
     */
    public cn.pojo.Nest.NestProto.Animal.Dog getDog() {
      return dog_ == null ? cn.pojo.Nest.NestProto.Animal.Dog.getDefaultInstance() : dog_;
    }
    /**
     * <code>.NestProto.Animal.Dog dog = 6;</code>
     */
    public cn.pojo.Nest.NestProto.Animal.DogOrBuilder getDogOrBuilder() {
      return getDog();
    }

    public static final int DINOSAUR_FIELD_NUMBER = 7;
    private cn.pojo.Nest.NestProto.Dinosaur dinosaur_;
    /**
     * <code>.NestProto.Dinosaur dinosaur = 7;</code>
     */
    public boolean hasDinosaur() {
      return dinosaur_ != null;
    }
    /**
     * <code>.NestProto.Dinosaur dinosaur = 7;</code>
     */
    public cn.pojo.Nest.NestProto.Dinosaur getDinosaur() {
      return dinosaur_ == null ? cn.pojo.Nest.NestProto.Dinosaur.getDefaultInstance() : dinosaur_;
    }
    /**
     * <code>.NestProto.Dinosaur dinosaur = 7;</code>
     */
    public cn.pojo.Nest.NestProto.DinosaurOrBuilder getDinosaurOrBuilder() {
      return getDinosaur();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dog_ != null) {
        output.writeMessage(6, getDog());
      }
      if (dinosaur_ != null) {
        output.writeMessage(7, getDinosaur());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dog_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getDog());
      }
      if (dinosaur_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getDinosaur());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.pojo.Nest.NestProto)) {
        return super.equals(obj);
      }
      cn.pojo.Nest.NestProto other = (cn.pojo.Nest.NestProto) obj;

      boolean result = true;
      result = result && (hasDog() == other.hasDog());
      if (hasDog()) {
        result = result && getDog()
            .equals(other.getDog());
      }
      result = result && (hasDinosaur() == other.hasDinosaur());
      if (hasDinosaur()) {
        result = result && getDinosaur()
            .equals(other.getDinosaur());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDog()) {
        hash = (37 * hash) + DOG_FIELD_NUMBER;
        hash = (53 * hash) + getDog().hashCode();
      }
      if (hasDinosaur()) {
        hash = (37 * hash) + DINOSAUR_FIELD_NUMBER;
        hash = (53 * hash) + getDinosaur().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.pojo.Nest.NestProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Nest.NestProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Nest.NestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Nest.NestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Nest.NestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.pojo.Nest.NestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.pojo.Nest.NestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.pojo.Nest.NestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.pojo.Nest.NestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.pojo.Nest.NestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.pojo.Nest.NestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.pojo.Nest.NestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.pojo.Nest.NestProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NestProto)
        cn.pojo.Nest.NestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.pojo.Nest.internal_static_NestProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.pojo.Nest.internal_static_NestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.pojo.Nest.NestProto.class, cn.pojo.Nest.NestProto.Builder.class);
      }

      // Construct using cn.pojo.Nest.NestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (dogBuilder_ == null) {
          dog_ = null;
        } else {
          dog_ = null;
          dogBuilder_ = null;
        }
        if (dinosaurBuilder_ == null) {
          dinosaur_ = null;
        } else {
          dinosaur_ = null;
          dinosaurBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.pojo.Nest.internal_static_NestProto_descriptor;
      }

      public cn.pojo.Nest.NestProto getDefaultInstanceForType() {
        return cn.pojo.Nest.NestProto.getDefaultInstance();
      }

      public cn.pojo.Nest.NestProto build() {
        cn.pojo.Nest.NestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.pojo.Nest.NestProto buildPartial() {
        cn.pojo.Nest.NestProto result = new cn.pojo.Nest.NestProto(this);
        if (dogBuilder_ == null) {
          result.dog_ = dog_;
        } else {
          result.dog_ = dogBuilder_.build();
        }
        if (dinosaurBuilder_ == null) {
          result.dinosaur_ = dinosaur_;
        } else {
          result.dinosaur_ = dinosaurBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.pojo.Nest.NestProto) {
          return mergeFrom((cn.pojo.Nest.NestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.pojo.Nest.NestProto other) {
        if (other == cn.pojo.Nest.NestProto.getDefaultInstance()) return this;
        if (other.hasDog()) {
          mergeDog(other.getDog());
        }
        if (other.hasDinosaur()) {
          mergeDinosaur(other.getDinosaur());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.pojo.Nest.NestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.pojo.Nest.NestProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private cn.pojo.Nest.NestProto.Animal.Dog dog_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.pojo.Nest.NestProto.Animal.Dog, cn.pojo.Nest.NestProto.Animal.Dog.Builder, cn.pojo.Nest.NestProto.Animal.DogOrBuilder> dogBuilder_;
      /**
       * <code>.NestProto.Animal.Dog dog = 6;</code>
       */
      public boolean hasDog() {
        return dogBuilder_ != null || dog_ != null;
      }
      /**
       * <code>.NestProto.Animal.Dog dog = 6;</code>
       */
      public cn.pojo.Nest.NestProto.Animal.Dog getDog() {
        if (dogBuilder_ == null) {
          return dog_ == null ? cn.pojo.Nest.NestProto.Animal.Dog.getDefaultInstance() : dog_;
        } else {
          return dogBuilder_.getMessage();
        }
      }
      /**
       * <code>.NestProto.Animal.Dog dog = 6;</code>
       */
      public Builder setDog(cn.pojo.Nest.NestProto.Animal.Dog value) {
        if (dogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dog_ = value;
          onChanged();
        } else {
          dogBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.NestProto.Animal.Dog dog = 6;</code>
       */
      public Builder setDog(
          cn.pojo.Nest.NestProto.Animal.Dog.Builder builderForValue) {
        if (dogBuilder_ == null) {
          dog_ = builderForValue.build();
          onChanged();
        } else {
          dogBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.NestProto.Animal.Dog dog = 6;</code>
       */
      public Builder mergeDog(cn.pojo.Nest.NestProto.Animal.Dog value) {
        if (dogBuilder_ == null) {
          if (dog_ != null) {
            dog_ =
              cn.pojo.Nest.NestProto.Animal.Dog.newBuilder(dog_).mergeFrom(value).buildPartial();
          } else {
            dog_ = value;
          }
          onChanged();
        } else {
          dogBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.NestProto.Animal.Dog dog = 6;</code>
       */
      public Builder clearDog() {
        if (dogBuilder_ == null) {
          dog_ = null;
          onChanged();
        } else {
          dog_ = null;
          dogBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.NestProto.Animal.Dog dog = 6;</code>
       */
      public cn.pojo.Nest.NestProto.Animal.Dog.Builder getDogBuilder() {
        
        onChanged();
        return getDogFieldBuilder().getBuilder();
      }
      /**
       * <code>.NestProto.Animal.Dog dog = 6;</code>
       */
      public cn.pojo.Nest.NestProto.Animal.DogOrBuilder getDogOrBuilder() {
        if (dogBuilder_ != null) {
          return dogBuilder_.getMessageOrBuilder();
        } else {
          return dog_ == null ?
              cn.pojo.Nest.NestProto.Animal.Dog.getDefaultInstance() : dog_;
        }
      }
      /**
       * <code>.NestProto.Animal.Dog dog = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.pojo.Nest.NestProto.Animal.Dog, cn.pojo.Nest.NestProto.Animal.Dog.Builder, cn.pojo.Nest.NestProto.Animal.DogOrBuilder> 
          getDogFieldBuilder() {
        if (dogBuilder_ == null) {
          dogBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.pojo.Nest.NestProto.Animal.Dog, cn.pojo.Nest.NestProto.Animal.Dog.Builder, cn.pojo.Nest.NestProto.Animal.DogOrBuilder>(
                  getDog(),
                  getParentForChildren(),
                  isClean());
          dog_ = null;
        }
        return dogBuilder_;
      }

      private cn.pojo.Nest.NestProto.Dinosaur dinosaur_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.pojo.Nest.NestProto.Dinosaur, cn.pojo.Nest.NestProto.Dinosaur.Builder, cn.pojo.Nest.NestProto.DinosaurOrBuilder> dinosaurBuilder_;
      /**
       * <code>.NestProto.Dinosaur dinosaur = 7;</code>
       */
      public boolean hasDinosaur() {
        return dinosaurBuilder_ != null || dinosaur_ != null;
      }
      /**
       * <code>.NestProto.Dinosaur dinosaur = 7;</code>
       */
      public cn.pojo.Nest.NestProto.Dinosaur getDinosaur() {
        if (dinosaurBuilder_ == null) {
          return dinosaur_ == null ? cn.pojo.Nest.NestProto.Dinosaur.getDefaultInstance() : dinosaur_;
        } else {
          return dinosaurBuilder_.getMessage();
        }
      }
      /**
       * <code>.NestProto.Dinosaur dinosaur = 7;</code>
       */
      public Builder setDinosaur(cn.pojo.Nest.NestProto.Dinosaur value) {
        if (dinosaurBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dinosaur_ = value;
          onChanged();
        } else {
          dinosaurBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.NestProto.Dinosaur dinosaur = 7;</code>
       */
      public Builder setDinosaur(
          cn.pojo.Nest.NestProto.Dinosaur.Builder builderForValue) {
        if (dinosaurBuilder_ == null) {
          dinosaur_ = builderForValue.build();
          onChanged();
        } else {
          dinosaurBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.NestProto.Dinosaur dinosaur = 7;</code>
       */
      public Builder mergeDinosaur(cn.pojo.Nest.NestProto.Dinosaur value) {
        if (dinosaurBuilder_ == null) {
          if (dinosaur_ != null) {
            dinosaur_ =
              cn.pojo.Nest.NestProto.Dinosaur.newBuilder(dinosaur_).mergeFrom(value).buildPartial();
          } else {
            dinosaur_ = value;
          }
          onChanged();
        } else {
          dinosaurBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.NestProto.Dinosaur dinosaur = 7;</code>
       */
      public Builder clearDinosaur() {
        if (dinosaurBuilder_ == null) {
          dinosaur_ = null;
          onChanged();
        } else {
          dinosaur_ = null;
          dinosaurBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.NestProto.Dinosaur dinosaur = 7;</code>
       */
      public cn.pojo.Nest.NestProto.Dinosaur.Builder getDinosaurBuilder() {
        
        onChanged();
        return getDinosaurFieldBuilder().getBuilder();
      }
      /**
       * <code>.NestProto.Dinosaur dinosaur = 7;</code>
       */
      public cn.pojo.Nest.NestProto.DinosaurOrBuilder getDinosaurOrBuilder() {
        if (dinosaurBuilder_ != null) {
          return dinosaurBuilder_.getMessageOrBuilder();
        } else {
          return dinosaur_ == null ?
              cn.pojo.Nest.NestProto.Dinosaur.getDefaultInstance() : dinosaur_;
        }
      }
      /**
       * <code>.NestProto.Dinosaur dinosaur = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.pojo.Nest.NestProto.Dinosaur, cn.pojo.Nest.NestProto.Dinosaur.Builder, cn.pojo.Nest.NestProto.DinosaurOrBuilder> 
          getDinosaurFieldBuilder() {
        if (dinosaurBuilder_ == null) {
          dinosaurBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.pojo.Nest.NestProto.Dinosaur, cn.pojo.Nest.NestProto.Dinosaur.Builder, cn.pojo.Nest.NestProto.DinosaurOrBuilder>(
                  getDinosaur(),
                  getParentForChildren(),
                  isClean());
          dinosaur_ = null;
        }
        return dinosaurBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NestProto)
    }

    // @@protoc_insertion_point(class_scope:NestProto)
    private static final cn.pojo.Nest.NestProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.pojo.Nest.NestProto();
    }

    public static cn.pojo.Nest.NestProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NestProto>
        PARSER = new com.google.protobuf.AbstractParser<NestProto>() {
      public NestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NestProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NestProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NestProto> getParserForType() {
      return PARSER;
    }

    public cn.pojo.Nest.NestProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NestProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestProto_Animal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NestProto_Animal_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestProto_Animal_Dog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NestProto_Animal_Dog_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestProto_Dinosaur_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NestProto_Dinosaur_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nnest.proto\"\254\001\n\tNestProto\022\"\n\003dog\030\006 \001(\0132" +
      "\025.NestProto.Animal.Dog\022%\n\010dinosaur\030\007 \001(\013" +
      "2\023.NestProto.Dinosaur\032*\n\006Animal\032 \n\003Dog\022\014" +
      "\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\032(\n\010Dinosaur\022\016\n" +
      "\006weight\030\004 \001(\001\022\014\n\004name\030\005 \001(\tB\017\n\007cn.pojoB\004" +
      "Nestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NestProto_descriptor,
        new java.lang.String[] { "Dog", "Dinosaur", });
    internal_static_NestProto_Animal_descriptor =
      internal_static_NestProto_descriptor.getNestedTypes().get(0);
    internal_static_NestProto_Animal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NestProto_Animal_descriptor,
        new java.lang.String[] { });
    internal_static_NestProto_Animal_Dog_descriptor =
      internal_static_NestProto_Animal_descriptor.getNestedTypes().get(0);
    internal_static_NestProto_Animal_Dog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NestProto_Animal_Dog_descriptor,
        new java.lang.String[] { "Name", "Age", });
    internal_static_NestProto_Dinosaur_descriptor =
      internal_static_NestProto_descriptor.getNestedTypes().get(1);
    internal_static_NestProto_Dinosaur_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NestProto_Dinosaur_descriptor,
        new java.lang.String[] { "Weight", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
